### ISSUE TITLE
Missing Spellcheck

### ISSUE THREAD

**Issue by andreykats** [yakyak/yakyak#336] opened 2016-08-10 18:18 UTC
I'm using version 1.2.5 (1.3.1) for Mac and it doesn't appear to have spell check enabled. Is this missing from the app?

**Comment by randymorris** [comment] 2016-08-10 20:14
#61

**Comment by davibe** [comment] 2016-10-11 14:10
closing as duplicate of https://github.com/yakyak/yakyak/issues/61

**Closed by davibe** 2016-10-11 14:10 UTC
