### ISSUE TITLE
Spell Check Support in Mac OS

### ISSUE THREAD

**Issue by mikedvzo** [yakyak/yakyak#816] opened 2017-11-17 02:40 UTC
Any chance of making the YakYak interface support the Mac OS default app right click menu to support spell checking.  My typing is so bad that without an auto spell checker this program is not usable.

**Comment by averissimo** [comment] 2018-01-13 23:50
The discussion on spell as you type is already being done for some time in issue #61 

To sum it up, it requires our releases to be compiled on each operating system *(instead of just one now)* and windows is hard to setup.

Additionally, we use an online service to do the building of the releases for us, which saves a lot of hassles, and we would prefer (highly) to keep it that way

Please take part in the discussion on that issue. I'm closing this as it is a duplicate of #61

**Closed by averissimo** 2018-01-13 23:50 UTC
