### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 () - To many new lines in message

### ISSUE THREAD

**Issue by KusioST** [yakyak/yakyak#574] opened 2017-02-02 13:03 UTC
I get error when I paste message with more new lines than can be visible in window. For example I make YakYak window very small and paste:

sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg
sssssss
ffffff
gggggg

![yakyak_error2](https://cloud.githubusercontent.com/assets/25057693/22550348/e5bfc4c4-e94f-11e6-9bcb-e6aedb6da281.jpg)

**Comment by averissimo** [comment] 2017-02-06 16:34
that error should not be related with the text, but with a strange profile image of one of your contacts that require authentication.

@KusioST Is this a duplicate of #242 ?

**Comment by KusioST** [comment] 2017-02-06 17:31
I can reproduce this error at any moment. When I send shorter message to this person everything is OK. I even don't need to send anything to get error. I just paste sample text and it appears.

**Comment by averissimo** [comment] 2017-02-07 13:46
This error will always appear. It is a private user image that YakYak cannot retrieve.

We perform the authentication process with the hangouts client _(a library called hangupsjs)_ and don't share the login with the window itself. Which gives 403 when trying to access this type of user images.

**Comment by KusioST** [comment] 2017-02-07 16:45
Ok. So there is nothing what can I do to prevent YakYak crush?

**Comment by averissimo** [comment] 2017-02-07 16:53
How does it crash? is there any problems with the UI?

**Comment by KusioST** [comment] 2017-02-10 15:40
This is how my chat window start to look after error. My contact list is cut to 5 people and I have big error notification.

![yakyak_crushed_window](https://cloud.githubusercontent.com/assets/25057693/22832758/961f2516-efaf-11e6-8c1e-99ef12d54cb9.jpg)
![yakyak_crushed_window2](https://cloud.githubusercontent.com/assets/25057693/22832687/51297556-efaf-11e6-9c63-0d1e094d49b3.jpg)

**Comment by mxyzplx** [comment] 2017-05-31 17:35
Often see the same thing. Noticed that if you open the inspector (to get the error code) and close it, everything goes back to normal.  This is with version. 1.4.4.

**Comment by KusioST** [comment] 2017-06-13 12:59
But it isn't normal behaviour, right?

**Comment by averissimo** [comment] 2017-07-24 23:57
that big error notification is not supposed to appear at all.. it is a placeholder for the "blank page" errors that we used to have

as soon as the application loads (i.e. connecting screen) this should never appear again.

can you guys trace anything you changed before this started to appear?

**Comment by KusioST** [comment] 2017-07-25 05:01
You will get it when You paste large text, but I can also do it for You,. What info You need?

**Comment by averissimo** [comment] 2017-07-25 10:51
got it!! Thanks

**Corrected the problem with the error page in latest pull request. Download 1.4.4 again or pull from master to get update**

The too many new lines interface problem is tracked somewhere else and not corrected

....

@KusioST one offtopic issue here as I'm taking advantage of you being active :)

Is yakyak still working for you? I've been having problems in the last week, but I moved to a crappy connection and it could be just me.

**Closed** 2017-07-25 10:52 UTC

**Comment by KusioST** [comment] 2017-07-27 05:40
Now it look better, but there is still something to fix. When I paste long text and delete it then YakYak window start looks like this:
![error_yak_yak](https://user-images.githubusercontent.com/25057693/28655836-9ce6d480-729e-11e7-9932-9fe020666bf7.jpg)
