### ISSUE TITLE
[feature request] add "Seen By"

### ISSUE THREAD

**Issue by Hongbo-Miao** [yakyak/yakyak#457] opened 2016-11-29 19:33 UTC
It will be great to add the feature "Seen By".
Thanks for the amazing app!

**Comment by averissimo** [comment] 2016-11-29 20:09
@Hongbo-Miao partial implementation in 1.4.0-beta3

see #451 and activate option via `view -> experimental`

The library that yakyak uses does not support (yet) having this information when opening a conversation, only after first interaction

**Comment by Hongbo-Miao** [comment] 2016-11-29 20:16
Thank you for the info!

**Comment by averissimo** [comment] 2016-11-29 20:28
duplicate of #87 closing.

**Closed by averissimo** 2016-11-29 20:28 UTC
Labels: enhancement
