### ISSUE TITLE
v1.5.4 MacOS (10.14.6) showing wrong number of unread messages

### ISSUE THREAD

**Issue by sfoley-gpqa** [yakyak/yakyak#1122] opened 2020-02-05 19:05 UTC
Heya,

First off, thanks for making such a great product. I use it every day at work. Really superior product.

I recently downloaded v1.5.4 for MacOS (10.14.6) and noticed every time I get a new message, it shows some large number (7-12) of new/unread messages in on the icon in the dock icon.

I've tried reopening the application, clicking the chat window to dismiss the number and waiting for another message. Every time a new message comes, instead of saying "1" it says a big number. I think it might be growing with the number of messages received(?)

Thank you for your time and assistance!

**Comment by averissimo** [comment] 2020-02-05 19:35
Try the v1.5.5. It should be solved in the beta version.

Duplicate of #1109

**Comment by sfoley-gpqa** [comment] 2020-02-05 19:35
Will do, thank you

**Closed by averissimo** 2020-02-05 19:35 UTC
