### ISSUE TITLE
Hangs on "Connecting" forever

### ISSUE THREAD

**Issue by exebook** [yakyak/yakyak#722] opened 2017-07-10 07:47 UTC
Yakyak does not start, it just displays it's logo, the word "Connecting" and the three animated dots underneath. I do not receive any timeouts, error messages, it just keeps animating three dots forever (or at least for 50 hours, as I left it open on Friday and it is still in the same state on Monday).

![selection_135](https://user-images.githubusercontent.com/3821217/28007730-c3aee74c-657e-11e7-8b9e-dc7cfee891d1.jpg)

I am on Ubuntu 16, 64 bit, and this is my first attempt to use this app.

**Comment by DavidBabel** [comment] 2017-07-12 15:14
Same problem on macos Sierra

**Comment by fuzzbawl** [comment] 2017-07-17 20:35
I was having the same issue, but after closing and opening again it works fine. I opened log console on macOS but didn't see anything jump out at me as an error.

**Comment by averissimo** [comment] 2017-07-25 00:06
can you guys try: https://github.com/yakyak/yakyak/releases/tag/v1.4.4-connecting

I've been having this problem for a while but I thought it was due to my crappy connection... seems like something else

note: i'm not getting thumbnails.. not sure if this is generalized

ps. if there are no binaries, just wait around 15 minutes

**Comment by totov** [comment] 2017-07-26 09:38
@averissimo that fix works for me 👍

**Comment by averissimo** [comment] 2017-07-26 11:49
@totov, a couple questions regarding your connection

- are you able to see all avatars?
- can you maintain a conversation? i.e. exchange messages back and forth?

Mine keep being shown as "sending" although they have been received on the other end

**Comment by totov** [comment] 2017-07-26 12:12
@averissimo 

Sorry, I haven't used it extensively, but from limited usage everything appears to be working as it should be (including avatars and message sending status).

**Comment by averissimo** [comment] 2017-07-26 12:56
cool!!

Nevertheless I think I traced down the "problem" and updated the backend a bit.. needs some more testing until released with yakyak though

Thanks for the feedback @totov _o_

**Comment by justinforce** [comment] 2017-08-08 23:49
I was able to get around this by reproducing [this change](https://github.com/yakyak/yakyak/commit/5d9b8338246de18ae9758e6a74ce4c90856b0913#diff-068bcf3f71a87e86883e2f6265d6e77aL51) by editing the compiled JavaScript locally.

```diff
*** /usr/share/yakyak/app/ui/models/viewstate.orig.js	2017-08-08 16:43:15.745342909 -0700
--- /usr/share/yakyak/app/ui/models/viewstate.js	2017-08-08 16:44:27.888881558 -0700
***************
*** 64,70 ****
      messageMemory: {},
      cachedInitialsCode: {},
      loadedContacts: false,
-     startupScreenVisible: true,
      openOnSystemStartup: false,
      setUseSystemDateFormat: function(val) {
        this.useSystemDateFormat = val;
--- 64,69 ----
```

YakYak v1.4.3 via [AUR](https://aur.archlinux.org/packages/yakyak/) on Manjaro 17.0.2

```
scsi:~% uname -a
Linux scsi 4.9.35-1-MANJARO #1 SMP PREEMPT Fri Jun 30 06:42:12 UTC 2017 x86_64 GNU/Linux
scsi:~% lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0.2
Codename:	Gellivara
```

**Comment by averissimo** [comment] 2017-09-16 13:22
@justinforce great debugging skills!!

Latest update to v1.4.4 has removed the "Loading contacts" from startup that could lead to this problem, as well as spread out the network calls over several calls

hopefully this will help in these situations!

Consider contributing your js skills to Yakyak!! we would welcome new code :)

**Closed** 2017-09-16 13:22 UTC

**Comment by uberubert** [comment] 2018-05-17 19:51
I'm experiencing this issue right now: Connecting (animated dots below) that seems to never finish, Not sure how to debug. V1.5.0

**Comment by matthewhively** [comment] 2018-05-17 20:30
Currently happening for me as well.

**Comment by hradec** [comment] 2018-05-17 21:07
same here!!
just installed the latest git in arch linux, and the same: 
![image](https://user-images.githubusercontent.com/806743/40203882-8f076832-59db-11e8-8cc9-69370c909e79.png)

maybe there's a recent change to the protocol?

**Comment by uberubert** [comment] 2018-05-17 21:15
I found an answer that worked for me.
My path was different, where I had to edit the file in [yakyak-directory]/resources/app/node_modules/hangupjs/lib/init.js

Gee, I hate the framework regime that governs most development these days.. Anyway, when I found the file, and made the described edit, my yakyak client was able to connect.

https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711

**Comment by Buggitt** [comment] 2018-05-18 04:56
@uberubert 
Had the same issue and this worked for me.

**Comment by combs** [comment] 2018-05-18 16:12
this is dying for me too now 😢

**Comment by tim-o** [comment] 2018-05-18 17:05
@combs did you try editing init.js as described here https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711?

Path in OS X for reference: /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js

**Comment by combs** [comment] 2018-05-18 17:30
Thanks--that did the trick!

**Comment by akaempf** [comment] 2018-11-01 15:04
Having same issues on WIndows 10... Just the connecting screen and never goes any further...

**Comment by arsradu** [comment] 2018-11-01 16:12
Same issues on MacOS. Not connecting, with or without editing that init.js file. Also, as a suggestion, maybe we could display a message when the app can't connect after a while? Is it timeout? Is there an error? Is the server down? It would help to know what's going on.

**Comment by LeoAlvarez** [comment] 2018-11-04 17:17
Same for me, edit or no edit on Mojave.

**Comment by ilganeli** [comment] 2018-11-05 18:29
For more info, here's the stack trace from running locally: ```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of null
    at /Users/ilganeli/code/yakyak/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:854:54)
    at /Users/ilganeli/code/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:816:13)
    at /Users/ilganeli/code/yakyak/app/node_modules/q/q.js:570:49
    at runSingle (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:137:13)
    at flush (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of null
    at /Users/ilganeli/code/yakyak/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:854:54)
    at /Users/ilganeli/code/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:816:13)
    at /Users/ilganeli/code/yakyak/app/node_modules/q/q.js:570:49
    at runSingle (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:137:13)
    at flush (/Users/ilganeli/code/yakyak/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
reconnecting 0
```

**Comment by ManifoldSky** [comment] 2018-11-08 07:11
On MacOS, open the app package and go to Contents/Resources/app/node_modules/hangupsjs/lib and change

 key: 'ds:20', to  key: 'ds:19',

Under both self_entity and conv_states.
Save, then relaunch app.

**Comment by ManifoldSky** [comment] 2018-11-08 07:32
Edited my post.
Blame Google for the constant need to tweak settings every few days!

**Comment by arsradu** [comment] 2018-11-08 08:04
> Edited my post.
> Blame Google for the constant need to tweak settings every few days!
> Also, if needed, consider going to /Applications/YakYak.app/Contents/Resources/app/ui/views/trayicon.js
> and commenting out the line:
> tray.setTitle(i18n.__('title:YakYak - Hangouts Client'));
> to stop the menubar icon from being obnoxious and taking up huge amounts of space with its title.

Thanks! Much appreciated!

**Comment by averissimo** [comment] 2018-11-09 17:03
Google is sucking especially hard, but we took too long to merge and release a fix that was already available. We really need some more active developers.

About the OSX tray issue, sorry guys... my bad see #990
