### ISSUE TITLE
Error: invalid_scope

### ISSUE THREAD

**Issue by lohfu** [yakyak/yakyak#358] opened 2016-08-30 12:48 UTC
Suddenly i cannot open yakyak.

All i get is a page with the following info:

```
400. That’s an error.

Error: invalid_scope

Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogin]

Learn more

Request Details
=
scope=https://www.google.com/accounts/OAuthLogin
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=936475272427.apps.googleusercontent.com
That’s all we know.
```

**Comment by davehalladay** [comment] 2016-08-30 14:23
Same for me, I just changed my Google account password and think that it may be related to that.

**Comment by CatLover91** [comment] 2016-08-30 15:13
I am getting this issue too, I just downloaded it and ran it. On startup, a loading indicator shows and then this error. OAuthLogin failing would make sense considering I hadn't even gotten to connecting my google account

**Comment by davehalladay** [comment] 2016-08-30 15:32
Should also mention I'm on Mac OSX El Capitan 10.11.6 running yakyak Version 1.2.5 (1.3.1)

**Comment by lohfu** [comment] 2016-08-30 16:03
@davehalladay i did just activate two factor authentication, but i created a new user (in Linux), ie no previous config, and tried starting yakyak with the same result.

**Comment by nickcoutsos** [comment] 2016-08-30 17:35
I'm getting the same on OSX (both Yosemite and El Capitan) and haven't changed my password or enabled 2-factor auth.

**Comment by jessejoe** [comment] 2016-08-30 17:54
Also getting this after deleting my `~/.config/yakyak` folder on Linux.

**Comment by jmlacroix** [comment] 2016-08-30 18:19
I just discovered YakYak and downloaded the app. When running it for the first time, I get the same error than @lohfu (OS X 10.10.4).

**Comment by downbeat210** [comment] 2016-08-30 20:05
same error. just discovered and downloaded so i haven't signed in yet, although I have also recently  (in the last 10 minutes) changed the password to one of my accounts. El capitan 10.11.6

**Comment by mydongistiny** [comment] 2016-08-31 03:04
This is the error I get when I get this screen.

hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
2016-08-30 19:57:54 WARN no SAPISID cookie
2016-08-30 19:57:54 WARN no SAPISID cookie
2016-08-30 19:58:10 WARN no SAPISID cookie
2016-08-30 19:58:10 WARN no SAPISID cookie

**Comment by davibe** [comment] 2016-08-31 06:27
Google has changed something :>

**Comment by wingedpanther** [comment] 2016-08-31 07:07
On windows 10 x64, 

@davibe "_Yes, google did something_"

![123](https://cloud.githubusercontent.com/assets/15865285/18119247/6901a536-6f62-11e6-8f70-2f7dabc4306a.png)

**Comment by oblitum** [comment] 2016-09-01 01:29
First time trying it here on ArchLinux, got same error, the application is unusable.

**Comment by oblitum** [comment] 2016-09-01 05:55
It's a general issue with third party clients as of now: https://productforums.google.com/forum/#!topic/hangouts/LU2YZNDhN_s. I guess we only have to wait until this is settled.

**Comment by MartSerra** [comment] 2016-09-01 15:07
Is there any update for fix this?. The app is useless if I cant login to Hangouts 😞

**Comment by eddielu** [comment] 2016-09-01 16:02
Having the same issue as well.

![image](https://cloud.githubusercontent.com/assets/6228169/18174550/8e3e110a-7033-11e6-9bb5-a8ad25b3d51c.png)

**Comment by CatLover91** [comment] 2016-09-01 16:50
It seems like Google disabled OAuth for all third party applications

> Hi guys, I confirm that this is a Google issue as of between 24 and 48 hours ago, something happened and Google probably changed the url of one of the servers it uses to delivers access tokens. Therefore the Pidgin Hangouts plugin that initiates requests for access codes directs its request to the wrong url, resulting in a oAuth 2.0 API throwing the now familiar error. 

>On Linux, Eion Robb, the developer of the Pidgin Hangouts plugin, informs via the sup...@pidgin.im mailing list that:
>> If you had previously been using it successfully and still have access to the old config, you could take the access/refresh token from the hangouts section of the ~/.purple/accounts.xml file on the working install and paste that into the accounts.xml file in the new install (while Pidgin isn't running)
Otherwise we'll have to wait until someone (or me) finds the new auth url to use. <<

>In other words eat yr hat if you must, but there is nothing you can do until Google moves on this.

[Source](https://productforums.google.com/forum/#!topic/hangouts/LU2YZNDhN_s)

**Comment by dequis** [comment] 2016-09-01 17:13
>It seems like Google disabled OAuth for all third party applications

No, that's just baseless speculation by someone who is neither a third party developer nor a google employee, it's not any sort of official statement.

If anything, it's more likely it's google doing internal unrelated changes. There is no official support for third party applications, they just don't care. We just use a reverse engineered implementation of the oauth flow used by the iOS hangouts app. They changed something in it, and we have to figure out what changed.

The reason why it affects all third party applications is that everyone copied the same auth flow from hangups.

**Comment by CatLover91** [comment] 2016-09-01 17:28
> No, that's just baseless speculation by someone who is neither a third party developer nor a google employee, it's not any sort of official statement.
Ah ok, I apologize. I do not wish to misinform

**Comment by oblitum** [comment] 2016-09-01 17:29
@dequis thanks for this clarification. What a sad state of matters to develop =/

**Comment by dandelucca** [comment] 2016-09-01 20:08
same issue here =/

**Comment by astralan** [comment] 2016-09-02 12:11
I was running version 1.2.5 at home without problems. At work I was using 1.2.1 and it crapped out beginning of week with all the aforementioned ailments. On a hunch, I packaged my home profile yakyak in the appdata/roaming folder (need to unhide everything) and the program files and unpacked them/replaced them at work and everything is working fine.

**Comment by Nezzeru** [comment] 2016-09-04 16:33
The same error in debian.
![captura de pantalla de 2016-09-04 11-32-13](https://cloud.githubusercontent.com/assets/9138004/18232338/55713692-7293-11e6-89a8-e4c0220732ec.png)

**Comment by oblitum** [comment] 2016-09-04 16:50
I guess no more reports of "same here" are needed. It seems clear it's happening for many.

**Comment by Sarabveer** [comment] 2016-09-04 17:24
Any way to manually create the config?

**Comment by orcinus** [comment] 2016-09-05 02:43
It happens when you change your password or switch to 2-factor auth (or revoke/invalidate YakYak's Google oAuth token in any other way).

It should be handling that exception (start the onboarding process again), but it doesn't.

**Comment by oblitum** [comment] 2016-09-05 04:22
For any new user of YakYak it's also not gonna work either.

**Comment by davibe** [comment] 2016-09-05 09:36
https://productforums.google.com/forum/#!msg/hangouts/LU2YZNDhN_s/nF9n8MEXDgAJ

**Comment by Finlay87** [comment] 2016-09-06 06:03
has this been fixed yet... pleeeease!?

**Comment by anishmalias** [comment] 2016-09-06 06:06
nop i dont know how to fix that issue..


*Anish M Alias*

*http://codehints.in/ <http://codehints.in/>*
https://anishalias00.wordpress.com/

**Comment by dandelucca** [comment] 2016-09-06 14:47
It looks like an authentication problem... I think they'll fix it soon

**Comment by emoruzzi** [comment] 2016-09-08 23:50
The chrome hangout extension was updated, which also seems to have changed the authentication/hangout process. 

http://googleappsupdates.blogspot.com/2016/08/a-new-google-hangouts-chrome-extension.html

**Comment by fancellu** [comment] 2016-09-10 08:50
We need yakyak more than ever. The new hangouts extension is an abomination. 

I get the above error as well.

**Comment by ricardoamaro** [comment] 2016-09-11 21:02
Same problem here...
```
$ ./yakyak 
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
```

400. That’s an error.
Error: invalid_scope
Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogin]

**Comment by mydongistiny** [comment] 2016-09-11 22:10
@ricardoamaro he knows it doesn't work. Read the thread. We don't need more me too posts.

**Comment by ricardoamaro** [comment] 2016-09-11 22:40
I noticed @mydongistiny . Thanks. This is an important piece of software that i can only think it would be important to confirm the root cause, so we can now where to watch. If that's indeed Google's problem where should we complain?

**Comment by oblitum** [comment] 2016-09-11 22:43
@ricardoamaro there's no place to complain. AFAIK this software and other third party clients are built by reverse engineering the official one.

**Comment by rferris** [comment] 2016-09-12 23:50
Alternative fix: convince everyone to move away from Google's lock-in chat client.

**Comment by wtowns** [comment] 2016-09-13 05:48
Looks like @dequis found a workaround: https://github.com/tdryer/hangups/issues/260#issuecomment-246578670

Confirmed that if you grab the auth using the mentioned method and hardcode it into src/login.coffee, the app works as expected.

**Comment by dequis** [comment] 2016-09-13 05:59
Given how yakyak uses electron and can load full web pages, it may be possible to integrate this the way it was intended to - in a webview, with something outside of the frame grabbing the cookie just like the iOS app does.

So you're lucky there, but for the rest of the hangups users we still have to find something better.

**Closed** 2016-09-13 12:55 UTC
Labels: bug, help wanted

**Comment by fancellu** [comment] 2016-09-13 13:19
Are there new binaries available?

**Comment by davibe** [comment] 2016-09-13 15:19
1.3.2 is in prepublish right now. Can you try and confirm it works so i can make it "public" ?

**Comment by dhleong** [comment] 2016-09-13 15:26
The OSX zip is a bit weird. Getting this error when I try to extract it:

<img width="382" alt="screen shot 2016-09-13 at 11 24 23 am" src="https://cloud.githubusercontent.com/assets/816150/18479951/de0008fe-79a4-11e6-843a-c26cdeea1f7a.png">

**Comment by osiride** [comment] 2016-09-13 15:31
1.3.2 works for me.

**Comment by cyocom** [comment] 2016-09-13 15:33
(the OS X app works if you unzip it from the command line)
If you log in using 1.3.2, then sign out, you return to the loop of 400 invalid_scope

**Comment by fancellu** [comment] 2016-09-13 15:34
Tried 1.3.2 on win32_x64, works lovely

**Comment by jessecarbon** [comment] 2016-09-13 15:37
Built on Debian 8, seems to be working. The first time running it just hung on "Connecting..." after logging in, but after a restart it's good :+1:

**Comment by jessejoe** [comment] 2016-09-13 15:38
Built on Debian 8, seems to be working. The first time running it just hung on "Connecting..." after logging in, but after a restart it's good :+1:

**Comment by dhleong** [comment] 2016-09-13 15:44
> (the OS X app works if you unzip it from the command line)

That worked, thanks! App's working great so far, OSX 10.11.6

**Comment by wickles** [comment] 2016-09-13 15:44
Also the OSX app still says version 1.2.5 in the file info. In the about window it says '1.2.5 (1.3.2)'.

**Comment by rbaaboud** [comment] 2016-09-14 11:14
Hi!

First of all, thanks for your amazing job.

Unfortunatly, the 1.3.2 doesn't work for me.
It was my first install of YakYak on my OS X 10.11.6. Never logged thought the app so.
I have: "400. That’s an error.
Error: invalid_scope
Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogin]"

Thanks for your help.

**Comment by jmlacroix** [comment] 2016-09-14 13:43
Works for me. First time user, never connected, OS X 10.10.4.

**Comment by skovmand** [comment] 2016-10-06 07:41
1.3.2 is good on Ubuntu 16.04 too. I had the 400 error before upgrading.
