### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Rudloff** [yakyak/yakyak#1234] opened 2020-09-09 22:46 UTC
When launching 1.5.9, it often crashes with the following error:
```
{
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/opt/yakyak/resources/app/ui/models/conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at /opt/yakyak/resources/app/ui/models/conv.js:42:34
      at add (/opt/yakyak/resources/app/ui/models/conv.js:49:9)
      at Object._initFromConvStates (/opt/yakyak/resources/app/ui/models/conv.js:522:17)
      at Object.init (/opt/yakyak/resources/app/ui/dispatcher.js:54:10)
      at doAction (/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:45:68)
      at action (/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/opt/yakyak/resources/app/ui/dispatcher.js:39:14)
      at file:///opt/yakyak/resources/app/ui/app.js:207:23
      at EventEmitter.<anonymous> (file:///opt/yakyak/resources/app/ui/app.js:105:16)
      at EventEmitter.emit (events.js:223:5)
}
```

It does not seem to happen everytime.

**Comment by vietk** [comment] 2020-09-10 08:53
I have the same error also

**Comment by JonTabor** [comment] 2020-09-11 13:06
I'm getting this error every time I start

**Comment by bleatingherd** [comment] 2020-09-11 16:28
Every launch for me as well.

```
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: 'C:\\Program Files\\YakYak\\resources\\app\\ui\\models\\conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at C:\Program Files\YakYak\resources\app\ui\models\conv.js:42:34
      at add (C:\Program Files\YakYak\resources\app\ui\models\conv.js:49:9)
      at Object._initFromConvStates (C:\Program Files\YakYak\resources\app\ui\models\conv.js:522:17)
      at Object.init (C:\Program Files\YakYak\resources\app\ui\dispatcher.js:54:10)
      at doAction (C:\Program Files\YakYak\resources\app\node_modules\trifl\lib\action.js:45:68)
      at action (C:\Program Files\YakYak\resources\app\node_modules\trifl\lib\action.js:21:12)
      at Object.init (C:\Program Files\YakYak\resources\app\ui\dispatcher.js:39:14)
      at file:///C:/Program%20Files/YakYak/resources/app/ui/app.js:207:23
      at EventEmitter.<anonymous> (file:///C:/Program%20Files/YakYak/resources/app/ui/app.js:105:16)
      at EventEmitter.emit (events.js:223:5)
}
```

**Comment by Collinormous** [comment] 2020-09-11 19:00
I've been receiving the same error with the deb package. The Snap package works fine though, but I find deb packages launch faster so I tend to use those primarily.

**Comment by orion4444** [comment] 2020-09-12 03:53
Same issue here on Windows 10.

**Comment by mstyles** [comment] 2020-09-14 15:49
Figured I would contribute mine as well, though it's the same error.
Specs:
Installation method: snap
version: 1.5.9
OS: Kubuntu 20.04

```
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/snap/yakyak/74/yakyak/resources/app/ui/models/conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at /snap/yakyak/74/yakyak/resources/app/ui/models/conv.js:42:34
      at add (/snap/yakyak/74/yakyak/resources/app/ui/models/conv.js:49:9)
      at Object._initFromConvStates (/snap/yakyak/74/yakyak/resources/app/ui/models/conv.js:522:17)
      at Object.init (/snap/yakyak/74/yakyak/resources/app/ui/dispatcher.js:54:10)
      at doAction (/snap/yakyak/74/yakyak/resources/app/node_modules/trifl/lib/action.js:45:68)
      at action (/snap/yakyak/74/yakyak/resources/app/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/snap/yakyak/74/yakyak/resources/app/ui/dispatcher.js:39:14)
      at file:///snap/yakyak/74/yakyak/resources/app/ui/app.js:207:23
      at EventEmitter.<anonymous> (file:///snap/yakyak/74/yakyak/resources/app/ui/app.js:105:16)
      at EventEmitter.emit (events.js:223:5)
}
```

**Comment by peppermintesse** [comment] 2020-09-16 19:37
Having the same issue, though I don't know where the log is to paste in entries (I've looked in ~/Library/Application Support/yakyak and in its subfolders, but I can't find anything relevant). :( 

It says the following message very briefly in the top right corner:

    Possible fatal error on main process, YakYak could stop working as expected.

After a few tries, it starts up. 

- **Installation method:** via the *.osx.zip download on https://github.com/yakyak/yakyak/releases
- **Version:** 1.5.9
- **OS:** macOS 10.15.6

Thanks :)

**Comment by Spleeen** [comment] 2020-09-19 07:11
In almost a year of use, I realize that this program has a lot of instabilities…

**Comment by myn** [comment] 2020-09-20 23:09
Perhaps we need to seek alternatives? The fact that this primary issue isn't assigned yet is telling to the maintainer status on this project.

**Comment by JonTabor** [comment] 2020-09-21 15:45
> Perhaps we need to seek alternatives? The fact that this primary issue isn't assigned yet is telling to the maintainer status on this project.

I have, temporarily at least, switched to Rambox.  I don't like it as well as yakyak, but it seems to work well enough.  I'm open to other alternatives, though of course I'd very much prefer to have yakyak working again.

**Comment by JonTabor** [comment] 2020-09-21 15:58
Okay, so I had a few minutes to look into this.  I forced yakyak to work by doing a bit of a stupid workaround.  In app/ui/model/conv.js, just after the 'event' variable is defined on line 32, I simply added this:

`event = "";`

This forces event to exist as an object (rather than being undefined), thus the call to check its length will be successful, allowing yakyak to run.  I don't know what I've broken doing this (if anything), but it appears to work.

**Comment by dep-dt** [comment] 2020-09-21 21:42
Thanks for the workaround @JonTabor that worked for me.

**Comment by orion4444** [comment] 2020-09-21 21:59
@JonTabor do you know the location of the `conv.js` file you mentioned for Windows users?

**Comment by JonTabor** [comment] 2020-09-21 23:50
> @JonTabor do you know the location of the `conv.js` file you mentioned for Windows users?

I pulled the code from git, then built it using the steps in the README. It'll have to be built for Windows with the modification; I'm not near my machine right now, but I'll build it for you tomorrow (if I can; I'm on Linux, so I may not have all the right "bits" installed to build for Windows).

**Comment by JonTabor** [comment] 2020-09-22 13:13
@orion4444 Alright, I was able to build the Windows version on my Linux system, but they are not small (like, 200+MB, larger than GitHub will let me post here).  No idea if they work, though.

**Comment by dep-dt** [comment] 2020-09-22 14:04
> @JonTabor do you know the location of the `conv.js` file you mentioned for Windows users?

I found `conv.js` at `resources/app/ui/models` in my `YakYak` program dir. Editing and relaunching seemed to work for me.

**Comment by jorrit** [comment] 2020-09-23 11:14
I changed line 42 to `for (j = 0, len1 = (event?.length || 0); j < len1; j++) {`.

**Comment by JonTabor** [comment] 2020-09-23 14:34
> I changed line 42 to `for (j = 0, len1 = (event?.length || 0); j < len1; j++) {`.

That's a better fix.

**Comment by kjg** [comment] 2020-09-23 14:38
I made this change to line 36 instead `({conversation, event = []} = conv);`

**Comment by Collinormous** [comment] 2020-09-23 15:22
> I made this change to line 36 instead `({conversation, event = []} = conv);`

This is the first one that's worked reliably for me. Thanks!

**Comment by baspetersnl** [comment] 2020-09-30 06:30
Problem still occurs after using the fix and starting an conversation with someone outside your conv list

**Comment by f1rmb** [comment] 2020-09-30 15:34
Hi,

   Same problem on Linux (LinuxMint 20). The PR  #1245 fixed the problem.

Cheers.
---
Daniel

**Comment by Collinormous** [comment] 2020-09-30 15:49
> Problem still occurs after using the fix and starting a conversation with someone outside your conv list

I can confirm this.

**Comment by kjg** [comment] 2020-09-30 16:14
> Problem still occurs after using the fix and starting a conversation with someone outside your conv list

This is a different issue, but can be fixed with 

`        if ((c != null && c.self_conversation_state ? c.self_conversation_state.view[0] : void 0) === 'ARCHIVED_VIEW') {`
on line 30 of  app/ui/views/convlist.js

**Comment by lasersocks** [comment] 2020-10-09 18:01
> > I made this change to line 36 instead `({conversation, event = []} = conv);`
> 
> This is the first one that's worked reliably for me. Thanks!

This solved my issue on ubuntu 20.04

**Comment by orion4444** [comment] 2020-10-09 18:02
Still no way to fix the Windows version without recompiling the binary.

**Comment by dep-dt** [comment] 2020-10-09 18:11
Is YakYak abandonware?

**Comment by kjg** [comment] 2020-10-09 18:17
> Is YakYak abandonware?

YakYak is open source software with an MIT license, meaning even if the current maintainers don't do things the way you like, anyone is free to take the code and make whatever modifications they which and redistribute it

**Comment by dep-dt** [comment] 2020-10-09 18:28
> anyone is free to take the code and make whatever modifications they wish

This works unless pull requests are ignored :(

**Comment by DwayneNeri** [comment] 2020-10-10 00:18
I cannot vouch for the validity/safety of the software, but I was able to install the Asar7z plugin for 7-Zip, open the app.asar package, find the file \ui\models\conv.js, and make the change to line 42 as indicated above.  This was for a Windows pre-built binary.  Technically, I made the change to 1.5.10-beta (as I had hoped the latest might have already fixed this).  I can confirm this finally made the issue go away.

Seems the modification to line 42 is the answer to life, the universe, and this pesky crash at launch.  Thank you @kjg !

**Comment by Fornero** [comment] 2020-10-10 05:36
In the address you mention that file does not exist in xubuntu 20.04
/opt/yakyak/resources/app/ui/models/conv.js

Also not which of all the solutions in # 1234 is the correct one
I guess this is the correct one
I changed the line 42 a for (j = 0, len1 = (event?.length || 0); j < len1; j++) {
but what file.

**Comment by gigecogary** [comment] 2020-10-12 14:49
> Is YakYak abandonware?

Yes

**Comment by jjs10** [comment] 2020-10-12 15:02
I was having the same issue on my Fedora Linux computer and wanted to post my fix for it here. After doing a fresh install of 1.5.9 I manually edited the /opt/yakyak/resources/app/ui/models/conv.js file by changing line 36 from:

`({conversation, event} = conv);`

to:

`({conversation, event = []} = conv);`

**Comment by lividhen** [comment] 2020-10-13 22:06
conv.js keeps getting over-writen when running npm run deploy:win32-x64, so i cant get any of the changes into the final bianary.

**Comment by peppermintesse** [comment] 2020-10-14 01:58
> I'm new to this and am unable to find this on my mac, could you per change let me know where I can find it? The terminal line would be perfect.
> 
> Thank you !

Hi there blondehouse--you have to:

1. Right-click on the YakYak app itself, then click **Show Package Contents**. 

1. Double-click **Contents > Resources > app > UI > models**. The file conv.js is in there--you should be able to edit that with a text editor like BBEdit.

I recommend duplicating the file before you edit it. If your edit goes sideways, you have a backup copy. 

Hope this helps.

**Comment by lividhen** [comment] 2020-10-14 02:55
https://www.tc4shell.com/en/7zip/asar/
I found an asar extension for 7z so you don't need to recompile for windows.

**Comment by blondehouse** [comment] 2020-10-15 15:20
> > I'm new to this and am unable to find this on my mac, could you per change let me know where I can find it? The terminal line would be perfect.
> > Thank you !
> 
> Hi there blondehouse--you have to:
> 
> 1. Right-click on the YakYak app itself, then click **Show Package Contents**.
> 2. Double-click **Contents > Resources > app > UI > models**. The file **conv.js** is in there--you should be able to edit that with a text editor like BBEdit.
> 
> I recommend duplicating the file before you edit it. If your edit goes sideways, you have a backup copy.
> 
> Hope this helps.
> 
> ETA: for me the path to this same file, for purposes of editing via pico or similar in Terminal, is **/Applications/YakYak.app/Contents/Resources/app/ui/models** .

Hi!

Thank you so much for your help! I tried this and the application would not start - saying that there was an error. I completely deleted the file, and reinstalled the latest beta. Now the file does not exist. Are you able to help at all?

Thank you!

**Comment by SovereignGFC** [comment] 2020-10-24 15:04
> I changed line 42 to for (j = 0, len1 = (event?.length || 0); j < len1; j++) {.

Confirmed this works for version 1.5.9 on October 24, 2020 after experiencing the issue of "possible fatal error in main process" when trying to start YakYak.

**Comment by lividhen** [comment] 2020-10-29 16:24
https://github.com/lividhen/yakyak/releases/tag/Final
For those who don't want to edit the file manually, I forked it, made the fix, then uploaded them as release.

**Comment by blondehouse** [comment] 2020-11-05 20:08
> https://github.com/lividhen/yakyak/releases/tag/Final
> For those who don't want to edit the file manually, I forked it, made the fix, then uploaded them as release.

Hi! I downloaded the release and it still wont work for me. Any other ideas?

**Comment by lividhen** [comment] 2020-11-06 18:27
> 
> 
> > https://github.com/lividhen/yakyak/releases/tag/Final
> > For those who don't want to edit the file manually, I forked it, made the fix, then uploaded them as release.
> 
> Hi! I downloaded the release and it still wont work for me. Any other ideas?

The mac one seems to not work, the windows one works for me, and i have not heard back on the linux one.

**Comment by AtmaDarkwolf** [comment] 2020-11-14 11:55
No offense to those who can get app to num the lines, but a 'change x to y' rather than just 'change line z to blahblahblah' would really help find the ORIGINAL line that needs changing. 

Thanks.

**Comment by mstyles** [comment] 2020-11-15 07:59
> No offense to those who can get app to num the lines, but a 'change x to y' rather than just 'change line z to blahblahblah' would really help find the ORIGINAL line that needs changing.
> 
> Thanks.

try this: https://github.com/yakyak/yakyak/pull/1245/files

**Closed** 2020-12-05 18:55 UTC
