### ISSUE TITLE
Support Multiple google accounts

### ISSUE THREAD

**Issue by eyadsibai** [yakyak/yakyak#302] opened 2016-07-02 12:17 UTC
I have two different gmail accounts that I would like to login with.

**Comment by invisiblegarage** [comment] 2016-07-06 18:46
Agreed. Great app. Would love support of mulitple google logins.

**Comment by davibe** [comment] 2016-07-07 14:39
we already talked about this. It require quite some effort but it's interesting.

**Comment by jlp78** [comment] 2016-08-22 15:41
This is a duplicate of https://github.com/yakyak/yakyak/issues/13

**Comment by davibe** [comment] 2016-09-19 12:16
closing as duplicate

**Closed by davibe** 2016-09-19 12:16 UTC
Labels: enhancement, help wanted
