### ISSUE TITLE
Stuck at Connecting after login.

### ISSUE THREAD

**Issue by ouoertheo** [yakyak/yakyak#983] opened 2018-10-25 22:48 UTC
I'm seeing the Connecting screen with the following repeated in the console. It never continues. I have 1.5.2.0 and upgraded from an older version to troubleshoot (probably at least 6 months old). I also tried clearing the yakyak folder in %appdata%. I'm using Windows 10 fully patched/updated.

`reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\hangupsjs\lib\init.js:125:21
    at _fulfilled (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:854:54)
    at C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:816:13)
    at C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:570:49
    at runSingle (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:137:13)
    at flush (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of undefined
    at C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\hangupsjs\lib\init.js:125:21
    at _fulfilled (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:854:54)
    at C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:816:13)
    at C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:570:49
    at runSingle (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:137:13)
    at flush (C:\Users\my.user.directory\Documents\My Apps\yakyak\resources\app\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

**Comment by Saur0o0n** [comment] 2018-10-26 07:51
Same problem on Linux since 23.10.2018
`hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
reconnecting 0
`

**Comment by beruic** [comment] 2018-10-26 08:17
I can confirm the bug. Here is what I get ( repeating over and over) on the current stable version (v1.5.1):
```verilog
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error connecting TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by plessbd** [comment] 2018-10-26 11:03
@beruic use https://github.com/yakyak/yakyak/releases/tag/v1.5.2 and the comments on #981 specifically https://github.com/yakyak/yakyak/issues/981#issuecomment-433029188 or https://github.com/yakyak/yakyak/issues/981#issuecomment-433124322

**Comment by embeddedt** [comment] 2018-10-26 15:11
Confirmed with 1.5.1. 1.5.2 works.

**Comment by averissimo** [comment] 2018-10-26 15:18
This is fixed in v1.5.2 that was just updated and released

Please report back if you guys have problems

**Closed by averissimo** 2018-10-26 15:18 UTC

**Comment by D661** [comment] 2018-10-26 17:43
> This is fixed in v1.5.2 that was just updated and released -- major thanks to contributors of this pull request: [yakyak/hangupsjs#104](https://github.com/yakyak/hangupsjs/pull/104)
> 
> Please report back if you guys have problems

1.5.2 doesn't fix this for me - but it says it was released 24 days ago, so I suspect I don't actually have the fix.

**Comment by D661** [comment] 2018-10-26 17:48
I'm using the win32-x64 zip. I see that it does have the updated code in hangups.js, and it is now working for me. No idea what went wrong the first couple times I tried, but disregard my previous comment, all is well now.

**Comment by beruic** [comment] 2018-11-01 08:41
I installed 1.5.2, and it worked, but somehow it doesn't now again.

What I get is
```
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of null
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of null
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
so pretty similar to the previous errors.

**Comment by beruic** [comment] 2018-11-01 08:44
Oh, I should mention the other differences:

1. No windows open at all.
2. Deleting the config before running makes the window appear, but is now stuck at connecting.

**Comment by embeddedt** [comment] 2018-11-02 00:11
@beruic Same problem for me as well.

**Comment by embeddedt** [comment] 2018-11-02 00:13
This workaround fixes it for now: https://github.com/yakyak/yakyak/issues/999#issuecomment-434873957
