### ISSUE TITLE
[ENCHANCEMENT] Adding better support for Phone Numbers/Contacts with GV and Hangouts/YakYak

### ISSUE THREAD

**Issue by andromedastudios1** [yakyak/yakyak#839] opened 2018-01-03 15:50 UTC
Hi all, 
This is an enhancement request; not sure how to change the label so whatever. 
Anyways, when GV (Google Voice) is linked with Hangouts, the person shown in the conversation list is the full phone number, not the name of the person that Hangouts/GV Sees. For example, if a recieve a text from +1 555 555 5555 and the name in Hangouts and GV is Bob Joe, YakYak shows +1 555 555 5555 and not Bob Joe. I don't have much programming experience, so anybody want to try? I could try to help and learn, but like I said, don't have much programming experience, let alone with the Hangouts/Google API.

**Comment by zpolygon95** [comment] 2018-01-03 22:24
As a Project FI user, I would love this feature as well! I'm not too experienced with JS (enough to be dangerous, and all that), but I'll see what I can do!

**Comment by lazyb5** [comment] 2018-01-04 01:37
Could you use google contact's API(if there is one) and match the phone number's with the user's contacts to display the name? I Know because I'm a android user all my contacts that I use with hangouts are synced

**Comment by averissimo** [comment] 2018-01-04 16:30
this is a duplicate of #232 some discussion on this topic and possible APIs have been discussed there

see this comment for the API https://github.com/yakyak/yakyak/issues/232#issuecomment-267233700

**Closed by averissimo** 2018-01-04 16:30 UTC

**Comment by andromedastudios1** [comment] 2018-01-04 16:31
Great! thanks for letting me know.
