### ISSUE TITLE
YakYak Crash on close

### ISSUE THREAD

**Issue by PMiner** [yakyak/yakyak#296] opened 2016-06-30 00:17 UTC
I have windows 10 x64 and downloaded the YakYak pre-release 1.3.1.
I have it set to keep in the dock, if that matters, and when i pressed close, i got this error.
`Uncaught Exception:`
`TypeError: Cannot read property 'isFullScreen' of null`
`    at BrowserWindow.<anonymous>`
`(C:\Users\*MyUser*\Downloads\YakYak\resources\app\main.js:443:21)`
`    at emitOne (events.js:96:13)`
`    at BrowserWindow.emit (events.js:188:7)`
`    at quit (C:\Users\*MyUser*\Downloads\YakYak\resources\app\main.js:100:9)`
`    at BrowserWindow.<anonymous>`
`(C:\Users\*MyUser*\Downloads\YakYak\resources\app\main.js:453:14)`
`    at emitOne (events.js:96:13)`
`    at BrowserWindow.emit (events.js:188:7)`

**Comment by monchote** [comment] 2016-07-01 11:14
This is fixed in master already. Duplicate of #278

**Closed** 2016-07-01 14:51 UTC
