### ISSUE TITLE
Hangouts logo on splash screen changes size on star up

### ISSUE THREAD

**Issue by mosbror** [yakyak/yakyak#471] opened 2016-12-02 08:01 UTC
This is really a minor bug.
The Hangouts logotype on the splash screen changes size when switching between "Connecting" and "Loading contacts".

[yakyak_ssize.mov.zip](https://github.com/yakyak/yakyak/files/626603/yakyak_ssize.mov.zip)

**Comment by averissimo** [comment] 2016-12-02 16:36
it doesn't on linux

cool catch :)

**Comment by averissimo** [comment] 2016-12-02 17:34
corrected in pull request #472 

thanks for reporting 👍

**Comment by averissimo** [comment] 2016-12-02 17:55
@mosbror actually, can you test if the fix works?

Find the binary here:

https://github.com/averissimo/yakyak/releases/download/test-icon/yakyak-472-1.4.0-darwin-x64.zip

**Comment by averissimo** [comment] 2016-12-02 19:34
actually, that can be a result of having a different zoom level set in yakyak

can you confirm that happens if zoom is at 100% (ctrl+0) ?

**Comment by Silveran** [comment] 2016-12-03 01:59
It works well for me with your version, just a little drop of the logo margin-top (not its size),it seems that the "Loading contacts" wording changes its font-size during the splashscreen.

**Comment by averissimo** [comment] 2016-12-03 15:05
i can't fix this blindly, seems like in Mac OS X the relative fonts and margins are changed just after connecting.

Can't reproduce this is linux or windows 7

needs someone to look at this :)

**Comment by Silveran** [comment] 2016-12-03 15:06
It's very better than before with your patch, don't worry, it's not important ;)

**Comment by mosbror** [comment] 2016-12-03 17:24
I agree with Silverian.

**Comment by averissimo** [comment] 2016-12-03 19:13
That's the first thing new users actually see when they try YakYak, should be clean :)

**Can you try this:** https://github.com/averissimo/yakyak/releases/tag/sandbox

**Comment by Silveran** [comment] 2016-12-04 00:03
@averissimo It works, you rock !!

**Comment by averissimo** [comment] 2016-12-04 00:17
PR #477

Thanks for reporting and feedback, closing the issue

**Closed by averissimo** 2016-12-04 00:17 UTC
Labels: bug
