### ISSUE TITLE
YakYak stopped working with Hangouts

### ISSUE THREAD

**Issue by tomasz-musialek** [yakyak/yakyak#979] opened 2018-10-24 17:07 UTC
HangupsJS stopped working about an hour ago due to the Google's renumbering of the fields in the HTML and as a result YakYak stopped working too.

Fixing the email field number in the "yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js" from "ds:36" to "ds:33" seems to solve the problem, so I suppose changing it here in the "src/init.coffee" file should do the trick.

We might need to renumber other fields too.

I think this will require a new binary release of YakYak too.

I created a pull request in the HangupsJS:

https://github.com/yakyak/hangupsjs/pull/102

**Comment by fulltrucker** [comment] 2018-10-24 17:14
I can confirm that changing the email field number in `/Applications/YakYak-darwin-x64/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js` from "ds:36" to "ds:33" allows YakYak to start up on Mac OS X El Capitan 10.11.6.

**Comment by Dustie** [comment] 2018-10-24 17:37
Fix works on Windows 10 too with newest binary.

**Comment by Gorklax** [comment] 2018-10-24 17:52
Fix also works on Linux mint.

**Comment by akholodenko** [comment] 2018-10-24 18:02
Worked on macOS Mojave 10.14

**Comment by DanLauer** [comment] 2018-10-24 18:05
> Fix works on Windows 10 too with newest binary.

Not for me.

**Comment by reaganking** [comment] 2018-10-24 18:19
Fix didn't work for me on Mojave 10.14

**Comment by zanthorn** [comment] 2018-10-24 18:20
> Fix didn't work for me on Mojave 10.14

Same here.

**Comment by Bukimari** [comment] 2018-10-24 19:01
Fix not working here either, Arch Linux x86_64 4.18.16

**Comment by shadowbottle** [comment] 2018-10-24 19:10
> I can confirm that changing the email field number in `YakYak-darwin-x64/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js` from "ds:36" to "ds:33" allows YakYak to start up on Mac OS X El Capitan 10.11.6.

Hmm... didn't work for me either. Mojave 10.14. YakYak just sits at Connecting...
<img width="876" alt="screen shot 2018-10-24 at 2 08 24 pm" src="https://user-images.githubusercontent.com/175063/47455070-8a4a6e00-d796-11e8-9eee-dc085a720b6f.png">

**Comment by thefence** [comment] 2018-10-24 19:17
Mojave 10.14 checking in, changing to ds:33 also did not work for me :(

**Comment by zackotronic** [comment] 2018-10-24 19:29
the fix worked at first, but now doesn't work as others are reporting.

**Comment by stevis** [comment] 2018-10-24 19:35
Mojave 10.14 here as well. That fix didn't work for me either. 😢

**Comment by fulltrucker** [comment] 2018-10-24 19:38
> I can confirm that changing the email field number in `YakYak-darwin-x64/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js` from "ds:36" to "ds:33" allows YakYak to start up on Mac OS X El Capitan 10.11.6.

YakYak is no longer working with this fix in place. Not sure what else I can do to help test or troubleshoot.

**Comment by elkinjosetm** [comment] 2018-10-24 20:09
The fix didn't work for me either. HELP!

**Comment by HomerSp** [comment] 2018-10-24 20:12
They changed it again to ds:31. But that's not the biggest problem, they've completely removed the data needed for conv_states, which means that no conversations will show up anymore.

**Comment by shadowbottle** [comment] 2018-10-24 20:30
> They changed it again to ds:31. But that's not the biggest problem, they've completely removed the data needed for conv_states, which means that no conversations will show up anymore.
> 
> EDIT: Forgot to mention, you'll also need to change self_entity to ds:20.

Ok, this is working for me now, but yeah, all my convos are gonezo along with history, etc. Obviously el goog is feeling a bit pissy regarding people making fun of Hangouts demise xD

**Comment by Bukimari** [comment] 2018-10-24 20:33
> They changed it again to ds:31. But that's not the biggest problem, they've completely removed the data needed for conv_states, which means that no conversations will show up anymore.
> 
> EDIT: Forgot to mention, you'll also need to change self_entity to ds:20.

Also allowing the client to connect for me as well, now I guess we wait for a fix for the conversations?

**Comment by reaganking** [comment] 2018-10-24 20:34
Yeah, I can open it now but no conversations in there and still feels like a bit of a mess.

**Comment by willgleich** [comment] 2018-10-24 20:34
My conversations just came back after making the ds:36 and ds:20 change.

**Comment by Bukimari** [comment] 2018-10-24 20:35
> My conversations just came back after making the ds:36 and ds:20 change.

You changed the email line back to ds:36 and changed self_entity to ds:20? Or am I misunderstanding that?

**Comment by Gedrean** [comment] 2018-10-24 20:37
Timestamp is ds:20 so what does that change to, if self_entity changes to ds:20 as well ??

That's probably why conversations are borked.

**Comment by Bukimari** [comment] 2018-10-24 20:39
> Timestamp is ds:20 so what does that change to, if self_entity changes to ds:20 as well ??
> 
> That's probably why conversations are borked.

Both timestamp and conv_states were already set to ds:20 so that doesn't necessarily mean that the values are conflicting.

**Comment by Gedrean** [comment] 2018-10-24 20:42
Nevermind I misunderstood how that works.

I can get up a blank black partially drawn window with no X in the corner if I use 36 and 20 or 31 and 20.

**Comment by shadowbottle** [comment] 2018-10-24 20:50
> My conversations just came back after making the ds:36 and ds:20 change.

I mean, I had to set mine to these to work at all, and no restored messages, even after restart. In fact, I lost the few messages I had accumulated after getting it to work the first time. Womp womp.

**Comment by sanimalp** [comment] 2018-10-24 20:58
I had to add a new conversation and send a message. but then @willgleich advice worked, and everything populated

**Comment by shadowbottle** [comment] 2018-10-24 21:05
> I had to add a new conversation and send a message. but then @willgleich advice worked, and everything populated

Care to list the steps you took to get messages back? I'm not really clear on the advice given or how it differs from what I've already done to get connections working. TIA!

**Comment by Bukimari** [comment] 2018-10-24 21:07
> > I had to add a new conversation and send a message. but then @willgleich advice worked, and everything populated
> 
> Care to list the steps you took to get messages back? I'm not really clear on the advice given or how it differs from what I've already done to get connections working. TIA!

Same, I assumed it meant changing email back to ds:36 but that just puts me back at square one with it unable to connect.

**Comment by willgleich** [comment] 2018-10-24 21:12
My messaged just populated after a conversation came through, clearly something is still misconfigured but atleast I'm not using the chrome extension in the mean time.

**Comment by sanimalp** [comment] 2018-10-24 21:12
> > > I had to add a new conversation and send a message. but then @willgleich advice worked, and everything populated
> > 
> > 
> > Care to list the steps you took to get messages back? I'm not really clear on the advice given or how it differs from what I've already done to get connections working. TIA!
> 
> Same, I assumed it meant changing email back to ds:36 but that just puts me back at square one with it unable to connect.

Sorry! I set 
`email: { key: 'ds:31',`
`self_entity: { key: 'ds:20',`

Then, when yakyak connected and appeared to load, I clicked the + sign, then typed in the contact name until it autocompleted, and then selected the contact. Then I sent a message. They sent me one back and all the history loaded.

**Comment by Bukimari** [comment] 2018-10-24 21:15
> > > > I had to add a new conversation and send a message. but then @willgleich advice worked, and everything populated
> > > 
> > > 
> > > Care to list the steps you took to get messages back? I'm not really clear on the advice given or how it differs from what I've already done to get connections working. TIA!
> > 
> > 
> > Same, I assumed it meant changing email back to ds:36 but that just puts me back at square one with it unable to connect.
> 
> Sorry! I set
> `email: { key: 'ds:31',`
> `self_entity: { key: 'ds:20',`
> 
> Then, when yakyak connected and appeared to load, I clicked the + sign, then typed in the contact name until it autocompleted, and then selected the contact. Then I sent a message. They sent me one back and all the history loaded.

Hmm, I've had a mini conversation with someone and it hasn't loaded my history back yet. Crap.

**Comment by reaganking** [comment] 2018-10-24 21:16
Confirming what @sanimalp said worked. History is back and chats both sending and receiving.

**Comment by shadowbottle** [comment] 2018-10-24 21:17
> > > > > I had to add a new conversation and send a message. but then @willgleich advice worked, and everything populated
> > > > 
> > > > 
> > > > Care to list the steps you took to get messages back? I'm not really clear on the advice given or how it differs from what I've already done to get connections working. TIA!
> > > 
> > > 
> > > Same, I assumed it meant changing email back to ds:36 but that just puts me back at square one with it unable to connect.
> > 
> > 
> > Sorry! I set
> > `email: { key: 'ds:31',`
> > `self_entity: { key: 'ds:20',`
> > Then, when yakyak connected and appeared to load, I clicked the + sign, then typed in the contact name until it autocompleted, and then selected the contact. Then I sent a message. They sent me one back and all the history loaded.
> 
> Hmm, I've had a mini conversation with someone and it hasn't loaded my history back yet. Crap.

TY Sanimalp for the steps! Same results as Bukimari here though - no reloading of history. I'm on MacOS Mojave, wonder if that might be part of it. I'm able to send and receive but message history is toast every time I reopen YakYak.

**Comment by Gedrean** [comment] 2018-10-24 21:17
I got history to work for SOME chats.

I would start a chat with someone, send something to get the chat to appear on the left.

Exit out of the chat (not out of YakYak) and then reopen the chat, and it would show the history for that chat.

It helps if I have a second chat to switch back and forth from.

Dammit Google, stop breaking everything!  What's your damn problem?

**Comment by reaganking** [comment] 2018-10-24 21:18
@shadowbottle did you try scrolling up? Mine didn't do it automatically. Once I tried to view history, it began fetching it.

**Comment by blackroseMD1** [comment] 2018-10-25 00:54
> Anyone else lose all their chats again if they restart YakYak? :(

Yeah. Every time, unfortunately.

**Comment by brianjlowry** [comment] 2018-10-25 01:19
I lost my converations initially, but then created a new one to a friend, sent "Test", and when he wrote back "Failed", it re-loaded our entire previous conversation.

**Comment by Cluuey** [comment] 2018-10-25 03:45
> > Anyone else lose all their chats again if they restart YakYak? :(
> 
> Yeah. Every time, unfortunately.

This happens for me too, very irritating as I have lots of conversations which can be very sporadic in nature.

The Google changes might have something to do with the G+ stuff.

**Comment by bobmorane83** [comment] 2018-10-25 09:44
Same here with Mojave 10.14 (fortunately threads are still available in google hangout interface).

**Comment by jmriego** [comment] 2018-10-25 10:29
@HomerSp your fix works for me in OSX! I just compiled it into js and modified the client.js and init.js files with those changes you made

**Comment by emmandyar** [comment] 2018-10-25 12:34
I have the same issue, however, I installed YakYak through snap, so I can't modify the files to apply the fix

**Comment by baspetersnl** [comment] 2018-10-25 14:02
tried this fix on Mac OS X Mojave and it worked. Even the history works.

[https://github.com/yakyak/hangupsjs/pull/104](url)

**Comment by alexriveraz** [comment] 2018-10-25 18:31
> I've created a pull request here that fixes these problems: [yakyak/hangupsjs#104](https://github.com/yakyak/hangupsjs/pull/104)
> Do give it a try if you can.

Thanks! @HomerSp ! I just compiled your code and merged into the Yakyak app in this path: /Applications/YakYak.app/Contents/Resources/app/node_modules/**hangupsjs**

It works, I'm using macOS Mojave 10.14

**Comment by Gedrean** [comment] 2018-10-25 21:06
Thanks to @HomerSp 's patches, on another issue that is the same as this issue, I have posted a set of steps that seem to fix this (applying the appropriate patched files) without the need to recompile.

This works for Win10 x64 but as others in the thread mention it works on Linux and Mac for them as well.

Here:

https://github.com/yakyak/yakyak/issues/981#issuecomment-433204393

**Comment by numbers1thru9** [comment] 2018-10-26 12:16
I can confirm that on Mojave 10.14 if you follow @Gedrean's link and download the init.js and client.js files from @ztoben (direct to files link here: https://gist.github.com/ztoben/41bd68f893f46fc055f52bbacbee30d2) and copy them to /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/ as long as you apply this patch to the pre-release version 1.5.2 it will launch normally with all convo history present. If you apply the patch to 1.5.1 you will get a java error and it will not launch.

**Comment by RobertFischer** [comment] 2018-10-26 13:32
I'm running [YakYak 1.5.1-0 on ArchLinux](https://aur.archlinux.org/packages/yakyak/). I applied [the `ds:*` changes described above](https://github.com/yakyak/yakyak/issues/979#issuecomment-432830091). That let me log in and at least start new conversations, although I lost my history.

However, when I click the burger bar, I then get:
```
Error on YakYak window:
 { columnNo: 24,
  error: {},
  lineNo: 221,
  msg: 'Uncaught Error: Could not call remote function \'\'. Check that the function signature is correct. Underlying error: Options must be an object\nError: Could not call remote function \'\'. Check that the function signature is correct. Underlying error: Options must be an object\n    at callFunction (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:257:11)\n    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:357:5)\n    at emitMany (events.js:147:13)\n    at EventEmitter.emit (events.js:224:7)\n    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:295:13)\n    at emitTwo (events.js:126:13)\n    at WebContents.emit (events.js:214:7)',
  url: '/usr/lib/electron/resources/electron.asar/renderer/api/remote.js' } 
```

**Comment by Bukimari** [comment] 2018-10-26 13:40
> I'm running [YakYak 1.5.1-0 on ArchLinux](https://aur.archlinux.org/packages/yakyak/). I applied [the `ds:*` changes described above](https://github.com/yakyak/yakyak/issues/979#issuecomment-432830091). That let me log in and at least start new conversations, although I lost my history.
> 
> However, when I click the burger bar, I then get:
> 
> ```
> Error on YakYak window:
>  { columnNo: 24,
>   error: {},
>   lineNo: 221,
>   msg: 'Uncaught Error: Could not call remote function \'\'. Check that the function signature is correct. Underlying error: Options must be an object\nError: Could not call remote function \'\'. Check that the function signature is correct. Underlying error: Options must be an object\n    at callFunction (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:257:11)\n    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:357:5)\n    at emitMany (events.js:147:13)\n    at EventEmitter.emit (events.js:224:7)\n    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:295:13)\n    at emitTwo (events.js:126:13)\n    at WebContents.emit (events.js:214:7)',
>   url: '/usr/lib/electron/resources/electron.asar/renderer/api/remote.js' } 
> ```

Check Issue [981](https://github.com/yakyak/yakyak/issues/981), it's got the full fix. I've also condensed a couple of seperate comments' worth of commands into one [here](https://github.com/yakyak/yakyak/issues/981#issuecomment-433095440). I'm running Arch as well and this fixed it perfectly for me.

**Comment by RobertFischer** [comment] 2018-10-26 13:57
@Bukimari --

I did exactly [the steps described here](https://github.com/yakyak/yakyak/issues/981#issuecomment-433095440), and this is what I've got:

```
Error: Cannot find module 'hangupsjs'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/share/yakyak-git/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/yakyak-git/resources/app/main.js:4:12)
    at Object.<anonymous> (/usr/share/yakyak-git/resources/app/main.js:598:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

[The files that I have are up in a gist](https://gist.github.com/RobertFischer/157862bec38e53d1102ca4bd2059e73e) to prove that `hangups` is still right where it should be...

**Comment by ztoben** [comment] 2018-10-26 14:10
@RobertFischer, there's no lib folder in your output of the hangoutsjs directory. Did you run `npm i` from the hangupsjs folder after replacing the src files and removing the old lib folder?

**Comment by Bukimari** [comment] 2018-10-26 14:10
@RobertFischer looking at your gist I'm seeing that while in the first one you can manually check the file directory it doesn't appear to be showing in the list when it checks the node_modules directory:
```
drwxr-xr-x  3 root   root   4096 Oct 26 09:49 har-schema
drwxr-xr-x  3 root   root   4096 Oct 26 09:49 har-validator
drwxr-xr-x  2 root   root   4096 Oct 26 09:49 has-flag
drwxr-xr-x  4 root   root   4096 Oct 26 09:49 he
drwxr-xr-x  3 root   root   4096 Oct 26 09:49 hexy
drwxr-xr-x 3 root root 4096 Oct 26 09:49 http-signature
```
That may explain the error you're receiving, however I'm not sure how you would go about fixing that if it's permission errors or what. When I run `ls -alR` on my box I get
```
drwxr-xr-x   6 justin justin  4096 Oct 26 09:03 hangupsjs
drwxr-xr-x   3 justin justin  4096 Oct 12 15:09 har-schema
drwxr-xr-x   3 justin justin  4096 Oct 12 15:09 har-validator
drwxr-xr-x   2 justin justin  4096 Oct 12 15:09 hosted-git-info
drwxr-xr-x   3 justin justin  4096 Oct 12 15:09 http-signature
```
when it checks node_modules.

**Comment by averissimo** [comment] 2018-10-26 14:33
The v1.5.2 build is being rebuilt right now and will be released in a few minutes, as soon as I can test it out

**Comment by averissimo** [comment] 2018-10-26 15:20
This is fixed in v1.5.2 that was just updated and released -- major thanks to contributors of this pull request: https://github.com/yakyak/hangupsjs/pull/104

Please report back if you guys have problems

**Closed by averissimo** 2018-10-26 15:20 UTC

**Comment by RobertFischer** [comment] 2018-10-26 15:28
@Bukimari @ztoben -- I would have sworn that I ran `npm i`, but I guess not...?

In any case, with the new release, ArchLinux's AUR `yakyak-git` package worked great for me out of the box.  (This was not the case this morning.)

**Comment by lparsons** [comment] 2018-10-29 14:40
Does anyone know if/when the snap package will get updated? Not really sure how that happens.

**Comment by averissimo** [comment] 2018-10-31 13:55
@OctoPenguin maybe knows

Snap package is community maintained.

**Comment by aroberts** [comment] 2018-11-01 18:53
I'm still having this problem on 1.5.2 (MacOS Mojave 10.14)

```
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of null
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:570:49
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of null
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:570:49
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by OctoPenguin** [comment] 2018-11-02 10:51
@averissimo I'll try updating it this weekend :)

**Comment by dionedarj** [comment] 2018-11-02 14:51
Receiving same issue as @aroberts on Fedora 28, Kernel 4.18.16-200.fc28.x86_64

**Comment by arcooke** [comment] 2018-11-02 20:38
Yakyak was working again for a while after installing the newest version but now I'm getting the same error as @aroberts

**Comment by fulltrucker** [comment] 2018-11-02 22:29
@hsergei have you tried the yakyak/hangupsjs#107 patch as [described here](https://github.com/yakyak/yakyak/issues/999#issuecomment-435510495)?

**Comment by hsergei** [comment] 2018-11-02 23:56
@fulltrucker just did try that too, same result. All patches include test/* files that I don't have. But looking at init.coffee after applying patch I do see email key changed from ds:31 to cic:vd so I don't believe patch failed to apply.

**Comment by hsergei** [comment] 2018-11-03 05:14
Nevermind - that did work. Missed rm -rf lib/* and rpm -i

**Comment by OctoPenguin** [comment] 2018-11-04 11:17
Okay, so I did the snap package but I don't have the credentials to push it to the Snap store. If someone could send me them somehow (email?) then I could do the push. Or I uploaded the file to OneDrive if someone else wants to push it.

**Comment by OctoPenguin** [comment] 2018-11-04 11:50
Okay, so I did the snap package but I don't have the credentials to push it to the Snap store. If someone could send me them somehow (email?) then I could do the push. Or I uploaded the file to OneDrive if someone else wants to push it.
