### ISSUE TITLE
yakyak not working on kali linux.

### ISSUE THREAD

**Issue by dev-deep** [yakyak/yakyak#932] opened 2018-05-28 05:39 UTC

**Comment by dev-deep** [comment] 2018-05-28 05:39
someone please help.

**Comment by rvaliant** [comment] 2018-05-28 14:11
https://github.com/yakyak/yakyak/issues/918#issuecomment-389772323

**Comment by Mange** [comment] 2018-05-28 18:26
Duplicate of #918. Please go in there and react with a +1 to vote it up.
I suggest you close this issue. :-)

**Closed** 2018-06-04 13:08 UTC
