### ISSUE TITLE
Multiple accounts add

### ISSUE THREAD

**Issue by tonyzorin** [yakyak/yakyak#879] opened 2018-02-15 09:35 UTC
Hangouts for iPhone supports multiple accounts, when someone sends to the second account I have to use my phone to reply. Any plans to support it?

**Comment by PiFi** [comment] 2018-02-20 06:05
sounds like it would take a lot of work, and the developers are stretched thin. you are better off trying to sandbox different instances.

**Comment by renatocn** [comment] 2018-04-24 19:38
Congrats for the work so far, nice app.

It could be great to have multiple accounts.

The last thing to be able to quit Adium.

**Comment by kwade00** [comment] 2018-05-30 19:39
There is an enhancement request: #13

**Comment by davibe** [comment] 2018-06-03 06:48
duplicate of #13

**Closed by davibe** 2018-06-03 06:48 UTC
