### ISSUE TITLE
error: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bewitchingme** [yakyak/yakyak#1304] opened 2021-01-15 18:04 UTC
Just installed YakYak 1.5.11 from .deb package on Ubuntu 18.04 and get the following after entering authentication details:

```
Starting Yakyak v1.5.11...
  using hangupsjs v1.3.10
--------

(yakyak:6524): Gtk-WARNING **: 13:02:19.060: Theme parsing error: gtk.css:6342:10: 'height' is not a valid property name
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/usr/lib/yakyak/resources/app.asar/ui/models/conv.js',
  lineNo: 520,
  columnNo: 32,
  error: TypeError: Cannot read property 'length' of undefined
      at Object._initFromConvStates (/usr/lib/yakyak/resources/app.asar/ui/models/conv.js:520:32)
      at Object.init (/usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:54:10)
      at doAction (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:45:68)
      at action (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:39:14)
      at file:///usr/lib/yakyak/resources/app.asar/ui/app.js:209:23
      at EventEmitter.<anonymous> (file:///usr/lib/yakyak/resources/app.asar/ui/app.js:107:16)
      at EventEmitter.emit (events.js:315:20)
      at Object.onMessage (electron/js2c/renderer_init.js:91:925)
} 
--- End of error message in YakYak window.
```

**Comment by AsgrimS** [comment] 2021-04-09 15:10
I have the same issue and after this error I'm also stuck at connecting.
Tried on the newest YakYak Release 1.5.11.1 as well as beta

**Comment by HomerSp** [comment] 2021-04-14 10:43
I'm currently looking at this issue, but as I'm unable to reproduce myself I'm going to need some more info. Any chance you could run yakyak with the --debug argument and post the output here. Remove any sensitive details such as emails or numbers from the output before posting.

**Comment by AsgrimS** [comment] 2021-04-15 07:35
@HomerSp Here you go, ran with the `--debug` argument and hopefully all personal data removed.

```Starting Yakyak v1.5.11.2...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-15 9:30:46 DEBUG emit connecting 
2021-04-15 9:30:46 DEBUG DEBUG: Received event connecting
2021-04-15 9:30:46 DEBUG getting auth...
2021-04-15 9:30:46 DEBUG using cached cookies
2021-04-15 9:30:46 DEBUG getAuth done
2021-04-15 9:30:46 DEBUG fetching pvt
2021-04-15 9:30:46 DEBUG request for https://clients6.google.com/chat/v1/clients/setactiveclient result: 403 {
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "errors": [
      {
        "message": "The request is missing a valid API key.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

2021-04-15 9:30:46 DEBUG request for 2 https://clients6.google.com/chat/v1/clients/setactiveclient result: 403 {
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "errors": [
      {
        "message": "The request is missing a valid API key.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

2021-04-15 9:30:46 DEBUG request for https://clients6.google.com/chat/v1/presence/setpresence result: 403 {
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "errors": [
      {
        "message": "The request is missing a valid API key.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

2021-04-15 9:30:46 DEBUG request for 2 https://clients6.google.com/chat/v1/presence/setpresence result: 403 {
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "errors": [
      {
        "message": "The request is missing a valid API key.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

2021-04-15 9:30:46 DEBUG init data count pvtToken 76
2021-04-15 9:30:46 DEBUG found pvt token 
{PVT TOKEN HERE}
2021-04-15 9:30:46 DEBUG initChat()
2021-04-15 9:30:46 DEBUG init data count apikey 39
2021-04-15 9:30:46 DEBUG init data count email 20
2021-04-15 9:30:46 DEBUG init data count headerdate 10
2021-04-15 9:30:46 DEBUG init data count headerversion 34
2021-04-15 9:30:46 DEBUG init data count headerid 16
2021-04-15 9:30:46 DEBUG init data timestamp 2021-04-15T07:30:46.770Z
2021-04-15 9:30:46 DEBUG init data self_entity {
  id: {
    gaia_id: '114814606059753378978',
    chat_id: '114814606059753378978'
  },
  properties: {
    type: 0,
    display_name: 'John Doe',
    first_name: 'John',
    photo_url: ' :smiley: ',
    emails: [ 'john.doe@mail.com` ],
    phones: [],
    in_users_domain: null,
    gender: null,
    photo_url_status: 2,
    canonical_email: null
  }
}
2021-04-15 9:30:46 DEBUG init data conv_states false
2021-04-15 9:30:46 DEBUG initializing recent conversations
2021-04-15 9:30:47 DEBUG request for https://clients6.google.com/chat/v1/conversations/syncrecentconversations result: 200 
2021-04-15 9:30:47 DEBUG found sid/gsid {sid/gsid here}
2021-04-15 9:30:47 DEBUG PushDataParser reset
2021-04-15 9:30:47 DEBUG emit connected 
2021-04-15 9:30:47 DEBUG DEBUG: Received event connected
2021-04-15 9:30:47 DEBUG long poll req
connected 0
2021-04-15 9:30:47 DEBUG Sending init...
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/usr/lib/yakyak/resources/app.asar/ui/models/conv.js',
  lineNo: 520,
  columnNo: 32,
  error: TypeError: Cannot read property 'length' of undefined
      at Object._initFromConvStates (/usr/lib/yakyak/resources/app.asar/ui/models/conv.js:520:32)
      at Object.init (/usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:54:10)
      at doAction (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:45:68)
      at action (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:39:14)
      at file:///usr/lib/yakyak/resources/app.asar/ui/app.js:209:23
      at EventEmitter.<anonymous> (file:///usr/lib/yakyak/resources/app.asar/ui/app.js:107:16)
      at EventEmitter.emit (events.js:315:20)
      at Object.onMessage (electron/js2c/renderer_init.js:91:925)
} 
--- End of error message in YakYak window.
```

**Comment by AsgrimS** [comment] 2021-04-15 07:36
Looks like forever-connecting status may come from invalid API key

**Comment by AsgrimS** [comment] 2021-04-15 08:15
I ran it on the YakYak 1.5.11.2 btw

**Comment by HomerSp** [comment] 2021-04-15 08:28
@AsgrimS Thanks for the output! I've actually been able to reproduce it now, so I'll release a fix momentarily. Basically, it happens when you don't have any active conversations on the logged in account (I tested it by logging in to an email address I had never used for hangouts before).

**Comment by HomerSp** [comment] 2021-04-15 09:36
@AsgrimS I've released v1.5.11.3 that should fix this issue - please test it and let me know if it works!

**Comment by AsgrimS** [comment] 2021-04-16 08:28
@HomerSp It's working now. Thank you

**Comment by HomerSp** [comment] 2021-04-16 09:28
@AsgrimS Great, thanks for confirming! I'll close this issue now (even though you didn't start the issue, the original one is the same thing).

**Closed by HomerSp** 2021-04-16 09:28 UTC
