### ISSUE TITLE
Images are all inverted... 

### ISSUE THREAD

**Issue by slbedard** [yakyak/yakyak#434] opened 2016-11-07 23:58 UTC
Specifically user images-- other images display fine. Changing color scheme doesn't affect this. 

![yakyak_and_gmail](https://cloud.githubusercontent.com/assets/233638/20081212/0d42ddba-a51c-11e6-8582-14d113108a7e.png)

edited by @averissimo as image was not displaying correctly

**Comment by chriscalo** [comment] 2016-11-08 14:05
To help track down the source of the issue, the color inversion goes away if you turn off **View** > **Show Animated Thumbnails**.

**Comment by averissimo** [comment] 2016-11-08 14:23
is this a duplicate of #120 ?

Can you try the fix by @aaronj1335 ?

**Comment by averissimo** [comment] 2016-12-22 15:45
closing as this is a duplicate. can you provide feedback there?

thanks

**Closed by averissimo** 2016-12-22 15:45 UTC
Labels: bug, help wanted
