### ISSUE TITLE
show status as online or show last seen timestamp

### ISSUE THREAD

**Issue by veasnalkj** [yakyak/yakyak#592] opened 2017-02-13 21:30 UTC
Can YakYak report that I am online?  For users using anything other than the new hangouts app, I appear to be offline when I'm using YakYak, although I will still receive messages sent to me.

**Comment by darrenmcentee** [comment] 2017-02-16 10:53
Similar to me, some of my contacts show an online status, even though i know they are offline.

**Comment by averissimo** [comment] 2017-02-16 17:50
Different bugs you guys are reporting :)

@veasnalkj yours is probably a duplicate of #167 that I'm attempting to correct in #596

@darrenmcentee i've noticed yours recently with some of my test contacts being online (which haven't been online for more than a week)

**Comment by veasnalkj** [comment] 2017-02-16 21:06
Thank you!  Yes, you’re correct.  Mine appears to be the same as #167.  Also, thanks for the response.  Just found YakYak about two weeks ago and I’m really enjoying using it.  Great product.

Lucas

**Comment by averissimo** [comment] 2017-02-22 15:35
@darrenmcentee this should be fixed in latests v1.4.2 pre-release, please try it.

Closing this issue as @veasnalkj is a duplicate of #167

**Closed by averissimo** 2017-02-22 15:35 UTC
Labels: bug
