### ISSUE TITLE
Windows: Google Notification for "New sign-in from Google Hangouts on *iOS*"

### ISSUE THREAD

**Issue by infogulch** [yakyak/yakyak#627] opened 2017-03-14 14:16 UTC
I just ran and singed into YakYak (yakyak-1.4.2-win32-x64) for Windows (Windows 10 Pro Version 10.0.14393 Build 14393 x64) and subsequently got an email from Google about a new sign in. Which is good and exactly what I expected.

What I didn't expect was Google to say that the sign in came from *iOS*:
![image](https://cloud.githubusercontent.com/assets/133882/23904591/6ca49e96-0896-11e7-8ea7-327811c88c53.png)

Any ideas?

**Comment by davibe** [comment] 2017-03-14 15:51
closin as duplicate of https://github.com/yakyak/yakyak/issues/104

**Closed by davibe** 2017-03-14 15:51 UTC
