### ISSUE TITLE
Translation of UI

### ISSUE THREAD

**Issue by Fredouye** [yakyak/yakyak#377] opened 2016-09-15 08:10 UTC
Hi

is the translation of UI planned ?

I volunteer for french language, if that can help :)

Thanks in advance.

**Comment by arnriu** [comment] 2016-09-15 10:54
https://github.com/yakyak/yakyak/issues/332

**Comment by davibe** [comment] 2016-10-11 14:15
closing as duplicate of https://github.com/yakyak/yakyak/issues/332

**Closed by davibe** 2016-10-11 14:15 UTC
