### ISSUE TITLE
Doesn't appear to work on Linux Mint

### ISSUE THREAD

**Issue by jcllings** [yakyak/yakyak#203] opened 2016-06-14 16:40 UTC
Just what the tittle says.

**Comment by TheSandman86** [comment] 2016-06-14 17:29
What is the problem?, could you be more specific?
What have you done so far?

**Comment by jcllings** [comment] 2016-06-14 17:31
Install it. Run it. Window pops up then disappears.

**Comment by randymorris** [comment] 2016-06-14 17:49
What version do you have installed?

**Comment by TheSandman86** [comment] 2016-06-14 22:37
Did you try to run it from the console? What message did it show?

**Comment by jreuter** [comment] 2016-06-23 13:56
I ran it from the console in Mint 17.1.  The window 'bounces' up and down as it's connecting.  Also, I have two-factor which might be the cause of the issue?  The terminal shows the following:

```
jarrod:yakyak-x64 $ ./yakyak 
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
2016-06-23 9:39:36 WARN no SAPISID cookie
2016-06-23 9:39:36 WARN no SAPISID cookie
2016-06-23 9:39:36 WARN no SAPISID cookie
2016-06-23 9:39:36 ERROR getAuth failed { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
connect_failed { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
error connecting { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
reconnecting 0

```

**Comment by averissimo** [comment] 2016-12-23 00:35
@jcllings @jreuter are you still experiencing this? (I'm closing for now since newer versions of YakYak may have corrected this, if not comment here and we'll reopen it :) )

since 1.4.0 the console is a bit more verbose about errors in the main window.

I also use 2-factor without a problem

the hangup could be a connection problem or a strange bug that is being tracked in #449

**Closed by averissimo** 2016-12-23 00:35 UTC
