### ISSUE TITLE
Notification problem with systray

### ISSUE THREAD

**Issue by mcanonic** [yakyak/yakyak#600] opened 2017-02-20 14:42 UTC
Hi,
in fedora 25 with classic Gnome, when I receive a new message I can see the pop-up notification and the systray icon becomes green. The problem is that in gnome classic, the systray did not show up even when the systray icon is green,
In the same situation, with pidgin, the systray icon has a blinking icon and the systray is not hiddden.
Last but not least: the icon in systray is really really small... too small.
Hope you can fix it, I really like yakyak.
M

**Comment by averissimo** [comment] 2017-02-21 19:33
Can you provide screenshots?

What version of gnome are you using?

**Comment by mcanonic** [comment] 2017-02-24 09:07
![screenshot from 2017-02-24 10-04-34](https://cloud.githubusercontent.com/assets/4497546/23297184/ccefdc74-fa78-11e6-929b-2adb7a7860bc.png)
In the attachment you can see the difference between pidgin icon and yakyak icon: it is almost invisible. I use the last version of gnome classic.
I think that here the problem is that my monitor is HiDPI screen, so if you use fixed size in pixel, it could be a problem when yur monitor can reach 3200x1800. I suggest to use relative size for icon.
M

**Comment by averissimo** [comment] 2017-02-24 12:20
Lol great catch!! I always wondered why icon was a bit smaller when testing in gnome :)

fixed in pull request #607

(closing)

**Closed by averissimo** 2017-02-24 12:20 UTC
Labels: bug

**Comment by averissimo** [comment] 2017-02-24 13:51
@mcanonic test latest build of 1.4.2 to confirm that it has been fixed.

Thanks

**Comment by mcanonic** [comment] 2017-02-24 14:45
Yes it better, now the problem is that you are not able to see when a 
new messagge arrived.

I can see the popup, but then it disappears and you are not able to 
notice that it is an unread message.

M

**Comment by averissimo** [comment] 2017-02-24 15:11
The icon turns green when there are unread messages, I guess the problem is that the tray is not always visible in gnome.

How does that work in Gnome with other messaging apps, or other type, that requires user-attention?

**Comment by averissimo** [comment] 2017-02-24 15:12
Unread message

![image](https://cloud.githubusercontent.com/assets/211358/23308588/92d740b0-faa3-11e6-82f1-1832c1047c62.png)

Read message

![image](https://cloud.githubusercontent.com/assets/211358/23308611/9e17bb3a-faa3-11e6-85d1-37bb786f5ac3.png)

**Comment by mcanonic** [comment] 2017-02-24 15:25
Yes, you are right but in pidgin you are able to be notified about new 
message since:

- it rises up the app window (it is a user option that you can switch 
on/off)

- the title bar is blinking so if you have minimized the app window, you 
can see the window title blinking (maybe you can just add an "*" in the 
title bar. The best would be to have the possibility to choose between 
"blinking title window" or "add an "*" on the tile window"). I other 
word the list of notification option should be improved.

I am not sure if it possible to force the systray to show up, this could 
be another option.

THanks!

M
