### ISSUE TITLE
Allow multiple google account

### ISSUE THREAD

**Issue by cacle-smile** [yakyak/yakyak#1153] opened 2020-05-04 08:02 UTC
It would be nice to be able to log on multiple google account at the same time.

**Comment by chaim-chv** [comment] 2020-05-06 11:05
hey @cacle-smile !! if you want simple way to use yakyak in two or more accounts:
i have a way - not for use **multiple accounts** on **one** instance of yakyak, but it very useful by my way,
edit the package.json file and change the name of the program in the line "name" to whatever you want. this will create a one copy of yakyak, and you can connect the new instance to other google account. you can do many instances in this way

i hope this will help you

**Comment by averissimo** [comment] 2020-05-07 15:04
duplicate of #13

**Closed by averissimo** 2020-05-07 15:04 UTC
