### ISSUE TITLE
Message input as part of each conversation

### ISSUE THREAD

**Issue by xedef** [yakyak/yakyak#139] opened 2016-02-12 16:44 UTC
It would be nice (and safer) that the message input depends on the conversation you're typing.
If you type a message, select another conversation, and hit <Enter>, the message is sent to the second one.
Altogether with the ⌘ + arrows shortcuts used to change conversations instead to go to the beginning/end of text, is easy to send the message to the wrong contact.

**Comment by algesten** [comment] 2016-04-08 20:35
duplicate of #76

**Closed by algesten** 2016-04-08 20:35 UTC
