### ISSUE TITLE
bunch of emoticons on message sidebar

### ISSUE THREAD

**Issue by kli0rf** [yakyak/yakyak#519] opened 2016-12-20 12:55 UTC
If there was least one emoticon used on last message, it shows the last message and all the emoticons of all previous messages in the sidebar message preview. Pretty odd.

**Comment by Arithmomaniac** [comment] 2016-12-20 18:39
Duplicate of #400 .

**Comment by averissimo** [comment] 2016-12-21 15:54
@kli0rf continue the discussion on #400

**Closed by averissimo** 2016-12-21 15:54 UTC
Labels: duplicate
