### ISSUE TITLE
Spaces do not work on arch linux

### ISSUE THREAD

**Issue by garethellis0** [yakyak/yakyak#240] opened 2016-06-19 12:38 UTC
There are no spaces in the conversations. The bottom text entry box is fine, but both messages sent and received have no spaces.

http://imgur.com/rwS5juK

**My Setup:**

- Node 6.2.2
- i3 version 4.11-404-gfdbe3ce
- npm 3.9.6
- libxtst 1.2.2-1
- gtk2 2.24.3

**Comment by davibe** [comment] 2016-06-19 16:04
lol, how is this happening

**Comment by Nepoxx** [comment] 2016-06-20 21:34
For what it's worth, I'm on arch and I do not have this issue (on gnome)

**Comment by jacobmischka** [comment] 2016-06-27 04:44
I also do not experience this issue on Arch on Gnome.

**Comment by PMiner** [comment] 2016-06-30 00:43
@garethellis0 what desktop do you use?

**Comment by garethellis0** [comment] 2016-06-30 00:49
@PMiner Sorry, not sure what you mean? The desktop is i3, but I specified that in the original post.

**Comment by Foxtrot** [comment] 2016-07-14 23:05
I am using yakyak on Awesome with the same issue, spaces are non existent. Is it a problem with tiling window managers?

**Comment by Foxtrot** [comment] 2016-07-14 23:14
Just quickly tested in LXDE on the same system, and the issue is still there :/

**Comment by garethellis0** [comment] 2016-07-19 01:07
Mine is the same as @Foxtrot describes.

**Comment by tommymh** [comment] 2016-08-16 19:30
I had the same issue on arch with i3wm, installed yakyak through the AUR.  After a bit of fiddling with the inspector, I found that the NotoColorEmoji font is the culprit.  I replaced the ttf file that came bundled with YakYak with the current one from google and that fixed the problem.

**Comment by Foxtrot** [comment] 2016-08-16 19:41
Interesting! Can you share where the .ttf yakyak uses is? I will try ASAP with my awesomeWM set up and see if it works.

**Comment by tommymh** [comment] 2016-08-16 19:44
I found it in: /usr/share/yakyak/resources/app/ui/css/noto-color-emoji/

**Comment by Foxtrot** [comment] 2016-08-16 20:08
Alright, so replacing it with the TTF from the Arch package doesn't fix it for me, but removing/renaming it does, and then YakYak works, sans-color emoji.

Good find and thanks for sharing @tommymh

**Comment by davibe** [comment] 2016-09-19 12:12
so should something be fixed in the code ? or can i close this ?

**Comment by tommymh** [comment] 2016-09-19 12:20
It's a font issue not a problem in the code, I think it can be closed.

**Comment by Foxtrot** [comment] 2016-09-20 14:04
Perhaps fix the font included in /usr/share/yakyak/... Not a code problem however.

**Closed** 2016-10-11 14:18 UTC
Labels: bug, help wanted
