### ISSUE TITLE
YakYak don't start. It hang on "connect" screen.

### ISSUE THREAD

**Issue by KusioST** [yakyak/yakyak#925] opened 2018-05-18 07:41 UTC
There is no error. I used YakYak before, but 3 days ago i must recover Windows. After it YakYak works, but then I must install some other programs, updates, and ad some fix to registry:
"reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters" /f /v AllowEncryptionOracle /t REG_DWORD /d 2"

After all this activity i reboot my PC and YakYak stop works.

**Comment by robkorv** [comment] 2018-05-18 08:08
I have this also on Ubuntu 14.04

**Comment by robkorv** [comment] 2018-05-18 08:09
Duplicate of #722

**Comment by KusioST** [comment] 2018-05-18 08:15
I don't think so. #722 is closed. So it may be similar or #722 wasn't fix?

**Comment by robkorv** [comment] 2018-05-18 08:26
Hmm, for some reason it autocompleted to the wrong issue. If you look at the issues there are two recent issues that have the same problem as me and you.

See https://github.com/yakyak/yakyak/issues/924 and https://github.com/yakyak/yakyak/issues/923.

**Comment by matusnovak** [comment] 2018-05-18 08:31
I have the same problem, all of the sudden YakYak stopped working 2-3 days ago (Windows x64). I have done no changes to Windows itself or YakYak. Have tried to install YakYak 1.5.0 from GitHub releases just now, it did not help. 

What helped was this: https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711

**Comment by robkorv** [comment] 2018-05-18 08:37
I also tried https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711. On which version did you change that line?

**Comment by KusioST** [comment] 2018-05-18 08:50
I have this same symptoms like @matusnovak have. It just stop work after reeboot and I also use Windows x64).
I try on yakyak-1.5.0 in both version: x32 and x64

**Comment by frazor** [comment] 2018-05-18 08:58
I tried fix in #918 on 1.4.4 (under macos, but should be the same really), and that worked. #919 will probably work too.

So fix should really work under both versions, 1.4.4 and 1.5.0.

**Comment by KusioST** [comment] 2018-05-18 09:00
In my case fix from #918 works. I test it on:
yakyak-1.5.0-win32-ia32.zip
yakyak-1.5.0-win32-x64.zip

**Comment by KusioST** [comment] 2018-05-18 09:01
https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711

**Comment by robkorv** [comment] 2018-05-18 09:43
https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711 indeed fixes it.
Be sure to edit `app/node_modules/hangupsjs/lib/init.js`.

I got it mixed up with the one at `node_modules/hangupsjs/lib/init.js`. (I run my yakyak from a local repository clone.)

**Comment by afogl001** [comment] 2018-05-18 12:07
I'm having the same problem on OpenSUSE Leap 42.3.  1.4.4 was working then just started hanging on the "Connecting" screen and upgrading to 1.5.0 didn't fix the issue for me.  I'm using tar balls for my installation method if that makes any difference

**Comment by robkorv** [comment] 2018-05-18 12:13
@afogl001 a bet that when they are unzipped and "installed" you will also find the file `app/node_modules/hangupsjs/lib/init.js`. Edit it like in https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711.

**Comment by afogl001** [comment] 2018-05-18 12:25
@robkorv. Thanks for your post, that did it!  Sorry, should have read your post closer!

**Comment by chadlavi** [comment] 2018-05-18 13:50
https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711 fixes it for me on macOS

**Comment by falterfriday** [comment] 2018-05-18 14:29
(https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711) fixes it for me on win10x64

**Comment by vutorious** [comment] 2018-05-21 13:58
[#919 (comment)](https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711) works for me - win7x64.  Just be sure to close the program entirely after making the change - you may have to use Task Manager.

**Closed** 2018-06-03 06:53 UTC
