### ISSUE TITLE
Connecting 'forever' 

### ISSUE THREAD

**Issue by ferranbonas** [yakyak/yakyak#1232] opened 2020-09-07 08:18 UTC
Yakyak MacOS client doesn't connect. I've uninstalled it and download/installed again (using 1.5.9). I'm using macOS Mojava 10.14.6. Yesterday it was working correctly.

Launching from command line throws this error:

```
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2020-09-07 10:11:11 WARN no SAPISID cookie
connect_failed Error: No auth headers
    at ChatReq.module.exports.ChatReq.baseReq (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/chatreq.js:31:25)
    at ChatReq.module.exports.ChatReq.req (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/chatreq.js:76:19)
    at Client.module.exports.Client.initrecentconversations (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:412:27)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:134:24
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:624:44
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
error connecting Error: No auth headers
    at ChatReq.module.exports.ChatReq.baseReq (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/chatreq.js:31:25)
    at ChatReq.module.exports.ChatReq.req (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/chatreq.js:76:19)
    at Client.module.exports.Client.initrecentconversations (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:412:27)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:134:24
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:624:44
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
```

**Comment by joshuacant** [comment] 2020-09-08 14:39
I'm also seeing this, on Windows. If I close it and open it over and over, eventually it will connect.

**Comment by cmurf** [comment] 2020-09-09 22:48
Same thing on Fedora 32.
npm-6.14.6-1.12.18.3.1.fc32.x86_64
nodejs-12.18.3-1.fc32.x86_64

```
$ cd ~/Applications/yakyak/ && npm run electron app &
[1] 255655
[chris@flap yakyak]$ 
> yakyak@1.5.10 electron /home/chris/Applications/yakyak
> electron "app"

Starting Yakyak v1.5.10...
  using hangupsjs v1.3.10
--------
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open i915 (search paths /usr/lib64/dri)
failed to load driver: i915
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib64/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
failed to load swrast driver
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/home/chris/Applications/yakyak/app/ui/models/conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at /home/chris/Applications/yakyak/app/ui/models/conv.js:42:34
      at add (/home/chris/Applications/yakyak/app/ui/models/conv.js:49:9)
      at Object._initFromConvStates (/home/chris/Applications/yakyak/app/ui/models/conv.js:522:17)
      at Object.init (/home/chris/Applications/yakyak/app/ui/dispatcher.js:54:10)
      at doAction (/home/chris/Applications/yakyak/app/node_modules/trifl/lib/action.js:45:68)
      at action (/home/chris/Applications/yakyak/app/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/home/chris/Applications/yakyak/app/ui/dispatcher.js:39:14)
      at file:///home/chris/Applications/yakyak/app/ui/app.js:209:23
      at EventEmitter.<anonymous> (file:///home/chris/Applications/yakyak/app/ui/app.js:107:16)
      at EventEmitter.emit (events.js:223:5)
} 
--- End of error message in YakYak window.
```

**Comment by cmurf** [comment] 2020-10-08 15:07
Also a problem on Fedora 33:
npm-6.14.8-1.14.13.0.1.fc33.x86_64
nodejs-14.13.0-1.fc33.x86_64
yakyak git b11ca5894
```
$ npm run electron app

> yakyak@1.5.10 electron /home/chris/Applications/yakyak
> electron "app"

Starting Yakyak v1.5.10...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/home/chris/Applications/yakyak/app/ui/models/conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at /home/chris/Applications/yakyak/app/ui/models/conv.js:42:34
      at add (/home/chris/Applications/yakyak/app/ui/models/conv.js:49:9)
      at Object._initFromConvStates (/home/chris/Applications/yakyak/app/ui/models/conv.js:522:17)
      at Object.init (/home/chris/Applications/yakyak/app/ui/dispatcher.js:54:10)
      at doAction (/home/chris/Applications/yakyak/app/node_modules/trifl/lib/action.js:45:68)
      at action (/home/chris/Applications/yakyak/app/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/home/chris/Applications/yakyak/app/ui/dispatcher.js:39:14)
      at file:///home/chris/Applications/yakyak/app/ui/app.js:209:23
      at EventEmitter.<anonymous> (file:///home/chris/Applications/yakyak/app/ui/app.js:107:16)
      at EventEmitter.emit (events.js:223:5)
} 
--- End of error message in YakYak window.
--------
```

**Comment by stephanieerin** [comment] 2021-04-13 13:59
Looks like this might be recreated by #1304 - I am still experiencing this infinite spin on connecting.

**Comment by HomerSp** [comment] 2021-04-13 20:34
@stephanieerin Are you also seeing the "Cannot read property 'length' of undefined" error? It looks to be different from the original issue, but I'm looking at the latter now and I am unfortunately unable to reproduce. Could you run yakyak with the --debug argument and post the output here? The data can contain sensitive information such as your email and phone number, so feel free to remove those. Thank you.

**Comment by stephanieerin** [comment] 2021-04-13 20:38
@HomerSp So I actually am not getting the length property issue but something else maybe entirely?

```
yakyak --debug
Starting Yakyak v1.5.10...
  using hangupsjs v1.3.10
--------

(yakyak:34336): Gtk-WARNING **: 16:35:56.710: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name

(yakyak:34336): Gtk-WARNING **: 16:35:56.720: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name

(yakyak:34336): Gtk-WARNING **: 16:35:56.721: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-13 16:35:57 DEBUG emit connecting 
2021-04-13 16:35:57 DEBUG DEBUG: Received event connecting
2021-04-13 16:35:57 DEBUG getting auth...
2021-04-13 16:35:57 DEBUG using cached cookies
2021-04-13 16:35:57 DEBUG getAuth done
2021-04-13 16:35:57 DEBUG fetching pvt
2021-04-13 16:35:57 INFO fetchPvt failed Unexpected token < in JSON at position 0
2021-04-13 16:35:57 DEBUG emit connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
2021-04-13 16:35:57 DEBUG DEBUG: Received event connect_failed
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
2021-04-13 16:35:58 DEBUG request for https://clients6.google.com/chat/v1/clients/setactiveclient result: 403 {
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "errors": [
      {
        "message": "The request is missing a valid API key.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

```

**Comment by HomerSp** [comment] 2021-04-13 20:42
@stephanieerin Ah yes, that's a different issue, see #1319. Google changed things on the server side, so you'll have to update to v1.5.11.2 :)

**Comment by HomerSp** [comment] 2021-04-17 07:26
The "Cannot read property 'length' of undefined" error has been fixed in the latest beta.

**Closed by HomerSp** 2021-04-17 07:26 UTC
