### ISSUE TITLE
Underscore wrong spelling not working

### ISSUE THREAD

**Issue by kamilko** [yakyak/yakyak#460] opened 2016-11-30 14:31 UTC
I don't know if this is electron issue or YakYak but autocorrect (red underscore) during writing is not working.
Version 1.3.3 and from master branch (90b7cb6).
OSX: 10.11.6

**Comment by averissimo** [comment] 2016-11-30 14:46
Not a bug, it is not implemented yet. We need someone to take this challenge :wink:

The original bug is #61 

ps. I'm closing this issue as it is a duplicate of that one :)

**Closed by averissimo** 2016-11-30 14:46 UTC
Labels: duplicate
