### ISSUE TITLE
Contacts not all working in YakYak

### ISSUE THREAD

**Issue by pricelessbrewing** [yakyak/yakyak#257] opened 2016-06-21 16:28 UTC
They're in my phone, synced, and on google contacts under the correct account, but yakyak just shows their phone number. I cannot see a way to import contact list either. Any ideas?

**Comment by davibe** [comment] 2016-06-26 08:35
We are not handling correctly contacts that are phones and not proper gmail contacts, i think

**Comment by katzly** [comment] 2016-07-12 23:14
i don't think the app is reading the contact list from google contacts. when using the official hangouts app to receive sms (instead of using google voice) the contacts don't have to be using the hangout in order for the contact info to populate, as long as the phone number and name are entered or saved in google contacts it will populate and show the name in hangouts. 

this is only true for hangouts on the desktop (which is pulling the info from your primary google mail/contacts). On the hangouts mobile, if you don't allow the app access to  your mobile address book, it will not populate the contacts names in the conversation.

it seems that you are using the mobile api (or connecter for hangouts as opposed to the desktop) because the "favorite" function for conversations is a mobile only feature and is unavailable on hangouts desktop. 

it would be great if you could somehow allow yak yak to access my google contacts address book to auto populate

**Comment by davibe** [comment] 2016-07-13 08:00
In yakyak `favourites` are only computed and saved on the client side. There is no interaction with special apis. I don't use yakyak to chat with sms/phones. I suspect in that case contacts have a different payload which we are not able to parse OR there is a special api we could use to access the user contacts to populate them.

**Comment by abrambailey** [comment] 2016-09-28 14:43
I would like a way to manually rename contacts in yakyak... Is that possible? I do a lot of chatting in hangouts over SMS, and I can't identify any of my friends in yakyak.

**Comment by AndrewJDR** [comment] 2016-12-15 16:37
This is a dupe of #232

**Comment by averissimo** [comment] 2016-12-15 19:43
@abrambailey @katzly @pricelessbrewing please continue discussing this in #232 as it has a small update

To manually rename contacts in yakyak it would need a similar structure to the favorites. 

But if that information can be retrieved from google contacts it would be a bit more clean. If someone feels like this should be a way to do it express that in #232 :)

**Closed by averissimo** 2016-12-15 19:43 UTC
Labels: bug, help wanted
