### ISSUE TITLE
Blue Tray Icon and Missing Window Titlebar

### ISSUE THREAD

**Issue by ElSenor64** [yakyak/yakyak#1195] opened 2020-06-30 15:33 UTC
Info:
- DE: MATE
- WM: Metacity (Marco)
- YakYak version: 1.5.8
- Install method: .deb file via gdebi

I just installed YakYak 1.5.8 and immediately got two strange errors:
1. The tray icon is now blue. I tried switching the YakYak theme just to make sure it wasn't a now feature (not that I would want a feature like that), and it didn't change. I tried switching my icon theme around and it didn't change. It is now blue, at least on the MATE DE.
2. The window's titlebar is now gone. It just disappeared. I found that I can click and drag the top of the window and it moves, but I have to use `Alt + Space` to manage anything else. In the screenshot I layered another window behind it to show that there is indeed a window titlebar on every other app.

These two things seem to be directly correlated with the new release (1.5.8); I uninstalled YakYak and re-installed version 1.5.7 and both problems are fixed (See the second screenshot).
Thanks!

Version 1.5.8:
![BUGS](https://user-images.githubusercontent.com/39417713/86145733-8404ad00-bab4-11ea-99ad-de1ec3e0ec69.png)
Version 1.5.7:
![UN-BUGS](https://user-images.githubusercontent.com/39417713/86145730-82d38000-bab4-11ea-95a9-ff87265eda6b.png)

**Comment by averissimo** [comment] 2020-06-30 17:40
The blue icon was a change to improve readability of yakyak read/unread for the color blind #1187 

For the window, seems like there's already a pull request #1196 

Closing this issue as this is a partial duplicate of #1194

**Closed by averissimo** 2020-06-30 17:40 UTC
