### ISSUE TITLE
Copying and pasting text from word uploads an image of same text

### ISSUE THREAD

**Issue by sbjustin** [yakyak/yakyak#46] opened 2015-08-11 20:46 UTC
If you copy and paste some text out of a word document yakyak will also upload an image of the same text.

**Comment by algesten** [comment] 2015-08-18 05:15
@davibe i guess this is your copy-past-image thing. word is probably both providing an image and a text object in the clipboard.

**Comment by davibe** [comment] 2015-09-06 14:29
ye, this is not related to #27 and i can reproduce using word on mac

**Comment by davibe** [comment] 2015-09-06 14:37
i changed things so that yak yak does not autosend image if clipboard also contains text. This is not optimal because sometimes copying an image also puts text in the clipboard. (like left click-ing an image in Safari and hitting 'copy image')

I am not sure how we can use limited electron apis to do something better.

**Comment by davibe** [comment] 2015-09-06 14:44
I am open to ideas, in the meantime i close this.

**Closed by davibe** 2015-09-06 14:44 UTC
