### ISSUE TITLE
OS X autocorrect does not function in text entry

### ISSUE THREAD

**Issue by jkuss** [yakyak/yakyak#237] opened 2016-06-17 21:21 UTC
It would be great if this worked.

**Comment by davibe** [comment] 2016-06-19 16:51
autocorrection is the first thing i disable everywhere on desktops :) but ok. If someone wants to jump-in could be a nice addition

**Comment by aPoCoMiLogin** [comment] 2016-07-27 09:34
Autocorrection is something i don't like too, but spell checker is fine and i'm missing it too.

**Comment by davibe** [comment] 2016-10-11 14:10
closing as duplicate of https://github.com/yakyak/yakyak/issues/61

**Closed by davibe** 2016-10-11 14:10 UTC
Labels: enhancement, help wanted
