### ISSUE TITLE
Error after 1.5.11.1 update

### ISSUE THREAD

**Issue by TheOmegaPope** [yakyak/yakyak#1324] opened 2021-04-09 17:43 UTC
Just trying to run the app after updating to 1.5.11.1 I get a message every time "AN ERROR HAS OCCURED"

It says to open the inspector but I am unsure how to do so as the app wont open and the link does nothing.
![image](https://user-images.githubusercontent.com/36393603/114220044-56407480-9920-11eb-84b1-3689cb25ecbf.png)

**Comment by HomerSp** [comment] 2021-04-11 07:58
Hi, what's your OS? Did you try clearing the yakyak user data folder? I'm unable to reproduce this myself, so will need more info.
If you run yakyak from a terminal/command prompt it should give you more info on why it fails in the output.

**Comment by boekabart** [comment] 2021-04-11 14:42
Same here after (chocolatey) upgrading to 11.1
Console output:
```
C:\ProgramData\chocolatey\lib\yakyak\tools\yakyak-win32-x64>yakyak.exe

C:\ProgramData\chocolatey\lib\yakyak\tools\yakyak-win32-x64>
(node:21936) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'getCurrentWindow' of undefined",
  url: 'C:\\ProgramData\\chocolatey\\lib\\yakyak\\tools\\yakyak-win32-x64\\resources\\app\\ui\\views\\convhead.js',
  lineNo: 138,
  columnNo: 25,
  error: TypeError: Cannot read property 'getCurrentWindow' of undefined
      at Object.<anonymous> (C:\ProgramData\chocolatey\lib\yakyak\tools\yakyak-win32-x64\resources\app\ui\views\convhead.js:138:25)
      at Object.<anonymous> (C:\ProgramData\chocolatey\lib\yakyak\tools\yakyak-win32-x64\resources\app\ui\views\convhead.js:168:4)
      at Object.<anonymous> (C:\ProgramData\chocolatey\lib\yakyak\tools\yakyak-win32-x64\resources\app\ui\views\convhead.js:172:3)
      at Module._compile (internal/modules/cjs/loader.js:1152:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
      at Module.load (internal/modules/cjs/loader.js:992:32)
      at Module._load (internal/modules/cjs/loader.js:885:14)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
      at Module.require (internal/modules/cjs/loader.js:1032:19)
      at require (internal/modules/cjs/helpers.js:72:18)
}
--- End of error message in YakYak window.

```

**Comment by boekabart** [comment] 2021-04-11 19:30
I'm pretty sure the problem is in the upgrade procedure: I've just downloaded the ZIP from here, extracted it to 
C:\ProgramData\chocolatey\lib\yakyak\tools
(the install location), after first renaming the existing folder there with an underscore for safekeeping.

Now it does work without issue.

When I try to start the other one again, error is back.

The only difference between the folder the installer left behind, and the fresh extraction of the zip, is the existence of a folder resources/app => in the fresh extract this is not present.

'Bad' version:
![image](https://user-images.githubusercontent.com/3244401/114318340-ec38f280-9b0c-11eb-8589-41c82a5ff930.png)

'Good' version:
![image](https://user-images.githubusercontent.com/3244401/114318396-f78c1e00-9b0c-11eb-9f23-9d3588c70b2d.png)

If I rename the `app` folder to `__app`, everything is hunky-dorey and works.

The file date of the `app` folder does seem to coincide with the moment that I did the upgrade.

**Comment by HomerSp** [comment] 2021-04-12 09:02
@boekabart Thanks for the detailed report! That app directory actually looks like a leftover from the 1.5.9 build (and older). If I extract 1.5.9 and just extract 1.5.11.1 over it I am able to reproduce the issue. It seems that, for some reason, it uses the app directory rather than the asar which explains why it's crashing because there are missing things due to it being an old build.
I'll see if I can somehow force it to use the asar, but as you noticed a quick workaround is to simply remove the resources/app directory. Thanks again.

**Comment by HomerSp** [comment] 2021-04-12 12:33
@boekabart Could you try v1.5.12 from here: https://github.com/yakyak/yakyak/releases/tag/v1.5.11.2 I've added a workaround that should fix it when you replace the files from an older install. Please let me know if it works!

**Comment by boekabart** [comment] 2021-04-12 13:46
I tried to do it the way I did the upgrade:
`choco upgrade yakyak -y`
But
`yakyak v1.5.11.1 is the latest version available based on your source(s).`

Manually copying the zip contents over the 'bad' version with the big app folder, works!

**Comment by HomerSp** [comment] 2021-04-12 17:10
@boekabart I think the choco repository is managed by someone else and has to be manually updated, so you will probably have to ask the maintainers of that for an upgrade.
Thanks for testing manually though, and glad to see that it works! I'll close this now since it's no longer an issue.

**Closed by HomerSp** 2021-04-12 17:10 UTC

**Comment by TheOmegaPope** [comment] 2021-04-13 18:20
The latest 1.5.11.2 update fixed my issue as well, sorry for the silence I was camping over the weekend. Cheers.
