### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by tk2** [yakyak/yakyak#844] opened 2018-01-05 11:01 UTC
Hi,
I'm was using yakyak quite happily but recently have been getting the following error (v1.5) on startup:

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadFromFile (/home/tk2/bin/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/home/tk2/bin/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/home/tk2/bin/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/home/tk2/bin/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/home/tk2/bin/yakyak-linux-x64/resources/app/main.js:49:12)
    at Object.<anonymous> (/home/tk2/bin/yakyak-linux-x64/resources/app/main.js:591:4)
    at Object.<anonymous> (/home/tk2/bin/yakyak-linux-x64/resources/app/main.js:595:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

Any help/advice would be appreciated.

Thomas

**Comment by averissimo** [comment] 2018-01-05 16:37
seems like a duplicate of #843 can you reply there with:

- Can you rename the config directory and run again to see if it works?
  - config directory is located at /home/tk2/.config/yakyak

If renaming works can you please show the first few characters in cookies.json *(please don't show the full contents of the file as it can have personal information)*

**Closed by averissimo** 2018-01-05 16:37 UTC
