### ISSUE TITLE
Feature Request: Spell Check

### ISSUE THREAD

**Issue by bs071** [yakyak/yakyak#361] opened 2016-08-30 19:32 UTC
Inline spell check requested

**Comment by monchote** [comment] 2016-09-01 10:25
Duplicate of #61

**Comment by randymorris** [comment] 2016-09-01 12:40
Someone really should consider closing some of these spell check tickets.  I think there are four of them now: #61, #237, #336, and this one.

**Comment by davibe** [comment] 2016-10-11 14:10
closing as duplicate of https://github.com/yakyak/yakyak/issues/61

**Closed by davibe** 2016-10-11 14:10 UTC
