### ISSUE TITLE
YakYak named 'Electron' in Windows 10 Task Manager

### ISSUE THREAD

**Issue by clrg** [yakyak/yakyak#580] opened 2017-02-07 12:46 UTC
Problem described in title. :)

Severity: as minor as it gets!

**Comment by averissimo** [comment] 2017-02-07 13:33
thanks for reporting!

**Comment by davibe** [comment] 2017-02-08 10:56
strange. Electron-packager bug ?

**Comment by averissimo** [comment] 2017-02-08 13:03
probably need to add some properties (see PR #583)

https://github.com/electron-userland/electron-packager/issues/30

solved with

https://github.com/electron-userland/electron-packager/pull/63

**Comment by averissimo** [comment] 2017-02-08 13:16
@clrg can you test current pre-release v1.4.2 it has been updated with PR  #583 that could fix this issue

it can be found: https://github.com/yakyak/yakyak/releases

cheers!

**Comment by averissimo** [comment] 2017-02-22 19:19
@clrg can you test current pre-release v1.4.2?

**Comment by clrg** [comment] 2017-02-22 19:58
It works properly in terms of it appears in the Task Manager as YakYak. However now I'm getting a random shortcut 'toast' appearing in my start menu which seems to be from the YakYak folder.

**Comment by averissimo** [comment] 2017-02-22 21:36
It is something that has been reported in the past and is related to notifications (a fallback notification system)

**Comment by averissimo** [comment] 2017-02-27 20:54
closing as the issue is solved

**Closed by averissimo** 2017-02-27 20:54 UTC
Labels: bug
