### ISSUE TITLE
Sent SMS texts stay gray

### ISSUE THREAD

**Issue by kethinov** [yakyak/yakyak#90] opened 2015-12-01 21:30 UTC
I'm using YakYak as a client for my SMS conversations with [Project Fi](http://fi.google.com) integrating my phone number into hangouts.

This enables text messages sent to my phone number to be routed through my hangouts account. I receive texts in YakYak.

I can reply (again routed through Project Fi) but the replies stay as gray text instead of showing as fully black text, indicating some kind of network error.

However, there is no network error and the texts do get sent correctly when I verify on my phone.

**Comment by swrobel** [comment] 2016-02-01 23:54
:+1:

**Comment by algesten** [comment] 2016-04-08 20:20
the gray is until we get some kind of confirmation back from the server. perhaps we never get that confirmation for these messages?

**Comment by jeffwllms** [comment] 2016-10-03 18:25
it doesn't as if the recipient receives the message.  I have he same issue.  sending to someone on project fi.  They are grey on my end and show on my phone.  But the receiver doesn't see them (on project fi).  I receive messages they send.

**Comment by dinoboy197** [comment] 2016-11-20 19:01
Confirmed as still an issue in version 1.3.3. I would love to use this client, but unfortunately, this problem prevents me from being able to switch from Google's client.

**Comment by natecox** [comment] 2017-03-08 01:02
I'm having this issue now as well. Is this on the radar for being fixed?

**Comment by davibe** [comment] 2017-03-14 13:44
@natecox There is no radar, just issues and pull requests. I don't see any PR about this so for now it's a no

**Comment by chazz422** [comment] 2017-07-11 16:44
This is a major problem with this app right now.  I've had several clients complain about not receiving my text messages.  Only happens with yakyak.  From hangouts client, it works fine.

Yes, it's strange how it shows up on the hangouts client on my phone as if they were sent, but they never get to the destination.

**Comment by natecox** [comment] 2017-09-10 22:35
This is certainly still an issue, commenting to prevent automated closing.

**Comment by averissimo** [comment] 2017-09-13 16:33
@natecox, can you help test a pull request that might address this issue?

**Comment by natecox** [comment] 2017-09-13 16:35
@averissimo Sure, which one?

**Comment by chazz422** [comment] 2017-09-13 16:37
I can help test also.

**Comment by averissimo** [comment] 2017-09-13 16:45
#738 or the `hawksprite-feature/google-voice-sms` newly created in yakyak/yakyak

For a binary file in 5 to 15 minutes there should be a release called v1.4.4-google-voice

__For this to work you need to__:

- activate an option called `Google Voice Mode` in main menu
- try to send an sms in a google voice conversation

note: this changes the way all messages are being sent in the client to use "google voice"... I'll try to change this if the pull request is working, but I'll need someone to test this out as I don't have access to a google voice account.

**Comment by chazz422** [comment] 2017-09-13 17:03
I checked the option for google voice like you mentioned, and sent a text to my wife through yakyak.  It works now!!!!!

Verified running on Linux.  Thanks for the update.

**Comment by jeffwllms** [comment] 2017-09-13 17:12
I have downloaded the client linked to, but I can't seem to find the setting that is suggested, can anyone provide any more detail?

**Comment by natecox** [comment] 2017-09-13 17:14
Looks like I'm able to receive SMS from Project Fi on the posted binary, using macOS. 

That being said, none of my contact information is being synced down, so all I can see are phone numbers and every avatar is a question mark (See below). I know on my iPad hangouts app I need to mark an option for "upload contacts" in order to get the contact information. Is there something similar I need to do here?

![screen shot 2017-09-13 at 10 13 36 am](https://user-images.githubusercontent.com/2782695/30390828-39449c5c-986c-11e7-89d0-dcad2fd1f6b0.png)

**Comment by natecox** [comment] 2017-09-13 17:15
@jeffwllms on macOS you can find it in the main menu.

![screen shot 2017-09-13 at 10 14 51 am](https://user-images.githubusercontent.com/2782695/30390907-6e131b8e-986c-11e7-9f69-96f974adb824.png)

**Comment by chazz422** [comment] 2017-09-13 17:16
Same problem here with ? mark in icons, but I believe that's a separate problem.

The problem with sending sms here is resolved for me.

**Comment by jeffwllms** [comment] 2017-09-13 17:19
Hep, sms appears to be working.  However just liek others it is now a question mark icon.  This is at least workable for now.

**Comment by jeffwllms** [comment] 2017-09-13 17:25
So, just on a side not it looks like mms, sending an image, etc. doesn't work

**Comment by averissimo** [comment] 2017-09-14 17:17
Ok, thanks for the feedback!! I'll try to improve on this "soon".

I have two question for you guys __see in #738 __

I'm closing this issue and moving the conversation there

**Closed by averissimo** 2017-09-14 17:17 UTC
Labels: bug

**Comment by averissimo** [comment] 2017-09-18 17:38
@jeffwllms @chazz422 if you guys are interested in helping out, please see my latest comment in pull request #738 

(or anyone else!!)

Thanks!
