### ISSUE TITLE
Can't text users by just using their phone number

### ISSUE THREAD

**Issue by Brothah-Heffay** [yakyak/yakyak#659] opened 2017-04-17 02:35 UTC
If I enter a number manually, I cant actually message that person whereas regular hangouts allows this.

This prevents messaging people who don't use hangouts.

**Comment by averissimo** [comment] 2017-04-18 19:19
this could be a duplicate of #330 

google voice is not correctly implemented in YakYak and we are looking for solutions

**Closed by averissimo** 2017-04-18 19:19 UTC
