### ISSUE TITLE
Emoji "pile up" in Conversations snippets

### ISSUE THREAD

**Issue by Arithmomaniac** [yakyak/yakyak#400] opened 2016-09-27 20:54 UTC
Any emoji I type in Yakyak seem to be permanently stuck at the end of the "Conversations" snippet.

See the attached screenshot, where it is stuck at the end of the _other_ participant's message, and contains emoji I used before my last message.

![screenshot 114](https://cloud.githubusercontent.com/assets/654897/18891399/a44284b2-84ca-11e6-8e18-c652737a3e7b.jpg)

**Comment by Arithmomaniac** [comment] 2016-09-28 14:03
This seems to reset every time I open the program

**Comment by averissimo** [comment] 2016-09-28 15:32
which OS and version of YakYak are you using? (can you try 1.3.3 and see if the "pile up" is still going on)

I don't see it in 1.3.3 (an in none of past versions)

![out](https://cloud.githubusercontent.com/assets/211358/18920364/15260f04-8599-11e6-9b92-74656c70bb49.gif)

**Comment by danfelbm** [comment] 2016-09-28 16:32
( Excuse me @averissimo , I apologize for the offtopic; but did you use any special tool to generate such gif easily? )

**Comment by danfelbm** [comment] 2016-09-28 17:51
(Sorry, also, how could you use hangout's icons in Mac OS? did you replace the font?)

**Comment by averissimo** [comment] 2016-09-28 18:14
**Offtopic 1:** Easily enough in any Linux system with two scripts working together and ffcast + avconv installed

I do them with one command (adding `-s -f` to select window)

    $ my_ffcast

Scripts here (just add them to your path):

https://gist.github.com/averissimo/3f40deac1ca22cc6658e2b2b56131ccc

For a windows and Mac I've read http://www.cockos.com/licecap/ is pretty good

**Offtopic 2:** Linux baby!! but seriously it comes pre-packaged in Yakyak, it was up to a certain version, removed by accident and then back in (I think).

If you install the Noto font system-wide then you also get it in YakYak (and by consequence in chrome)

Again in Linux there is a tweak necessary ::angry emoji here::, see my comments in #132

**Comment by averissimo** [comment] 2016-09-29 12:04
@Arithmomaniac sorry for the offtopic responses, did updating YakYak solve the problem? or is still persists in latest version?

**Comment by Arithmomaniac** [comment] 2016-09-29 13:21
Haven't had a chance to test yet. Will update when do

-----

**Comment by Arithmomaniac** [comment] 2016-09-30 17:17
Got a chance.
It seems that every time I send an emoji, it and the subsequent text in the body, get stuck to the end of the preview snippet.

**Comment by averissimo** [comment] 2016-09-30 18:30
Super strange!!

Which opeating system are you using? 

Is there any warning/error on the console (press Ctrl + Shift + I) and open the console tab.

If you can paste it here. Thanks

**Comment by Arithmomaniac** [comment] 2016-09-30 19:21
Windows 10.

![screenshot 115](https://cloud.githubusercontent.com/assets/654897/19003985/08ab8da4-8719-11e6-8ac6-5bc850e634bd.jpg)

**Comment by averissimo** [comment] 2016-09-30 20:18
I also have that error lol. Any other?

Does your recipient see the original message? or the "piled up emojis" version you see

**Comment by Arithmomaniac** [comment] 2016-10-02 20:08
The original message.

**Comment by averissimo** [comment] 2016-11-29 18:51
@Arithmomaniac that error is corrected in latest 1.4.0-beta release, can you test it and see if problem still appears

see #451 to download beta (sorry in advance for more repeated comments)

**Comment by Arithmomaniac** [comment] 2016-12-20 18:38
I still see this issue in 1.4.0.

**Comment by averissimo** [comment] 2016-12-20 19:54
@Arithmomaniac **is this only for the snippet?** or this also happens in the message pane

**Comment by kli0rf** [comment] 2016-12-21 14:26
Hi, @averissimo,
in my case this only happens for conversations sidebar. Here's the screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/18033767/21392757/17cf2630-c79a-11e6-8ea1-38a920071a71.png)

Windows 7 32, YakYak v1.4.1

**Comment by averissimo** [comment] 2016-12-21 16:01
If someone is interested in trying to figure this one out

The snipped is being drawn in `src/ui/views/convlist.coffee`

I would suggest starting by adding a breakpoint (or a `console.log('e',e)`) in the first line of `drawMessage` function to see what is the contents of `e` (the chat event) and namely `e.chat_message.message_content`

After that either the contents are correct and is the formatting that breaks this, or the problem is upstream _(how we choose the last message or even how that is kept in the conversation)_

Anyway, I can't reproduce this at all so someone has to pick this up and investigate :)

**Comment by averissimo** [comment] 2017-02-27 20:36
@kli0rf @Arithmomaniac can you confirm that this is still happening?

@davibe made a correction in windows that should have solved this problem.

**Comment by kli0rf** [comment] 2017-02-28 11:15
@averissimo i've just unpacked version 1.4.2 (released by You 4 days ago). Looks ok so far. Gonna let You know if that happens again. Thank You!

**Comment by kli0rf** [comment] 2017-02-28 16:47
@averissimo btw, now all emoticons are colourless. I'm not sure if that's intented though... Just sayin'. :)

**Comment by Arithmomaniac** [comment] 2017-02-28 20:16
Works for me now! And mine have color. Thanks!

**Comment by kli0rf** [comment] 2017-02-28 21:21
My bad, i thought yakyak's using it's own integrated emoticons... Just noticed it's an emoji font we're talking about, so colourless emojis are completely windows 7 problem. Please ignore my previous post.

**Comment by averissimo** [comment] 2017-03-01 16:23
Yeah, that is something we probably have to tackle before releasing 1.4.2

The way it was being done injected snippets in weird places and we removed and defaulted to windows emoji font (that is colorless)

anyway @kli0rf that is being tracked in #568

I'm closing this issue as it has been corrected

**Comment by averissimo** [comment] 2017-03-01 16:23
btw, major props to @davibe that corrected this bug! :)

**Closed by averissimo** 2017-03-01 16:23 UTC
Labels: bug

**Comment by Arithmomaniac** [comment] 2017-03-01 17:08
What commit fixed it?

**Comment by averissimo** [comment] 2017-03-01 18:26
I think this one: ec1c6b41583e712d3c2316f9812f7c832feeca34
