### ISSUE TITLE
Wrong Icon in KDE Systray

### ISSUE THREAD

**Issue by JPRuehmann** [yakyak/yakyak#807] opened 2017-11-04 10:27 UTC
![screenshot_20171112_105020](https://user-images.githubusercontent.com/4321829/32697791-b89f68aa-c798-11e7-987f-335c822ab98a.png)
Hello
In my Systray Yakyak displays only a Filter Icon not the Programm Logo.
How can I change that?
Thanks,

**Comment by davibe** [comment] 2017-11-12 16:04
@averissimo you have any idea why is that ?

**Comment by gusarg81** [comment] 2017-11-27 12:26
Hi,

   Is not a "filter icon", is the App icon that display so huge. Same happened to me and already filled an issue abou this before: #788

**Comment by JPRuehmann** [comment] 2017-11-27 12:29
Ok, hope there will be an Update in the near Future.
Thanks,

**Comment by gusarg81** [comment] 2017-11-27 12:31
It seems that is a problem with Electron (https://electronjs.org/), which is the Framework they use to develop this app. So every Electron based app, seems to have this problem in KDE.

Developers: I am right?

**Comment by averissimo** [comment] 2018-01-05 17:06
Closing this issue as it is a duplicate of #788 thanks for reporting

Let's continue discussion there :)

**Closed by averissimo** 2018-01-05 17:06 UTC
