### ISSUE TITLE
Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by subsumo** [yakyak/yakyak#106] opened 2016-01-07 15:09 UTC
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
version.coffee:20 YakYak local version is 1.1.1, released version is 1.1.1

/Applications/YakYak.app/Contents/Resources/app/node_modules/trifl/lib/view.js:126 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

18/Applications/YakYak.app/Contents/Resources/app/node_modules/trifl/node_modules/virtual-dom/vdom/pa…:27 Uncaught TypeError: Cannot read property 'ownerDocument' of null

**Comment by solocommand** [comment] 2016-12-14 14:20
@davibe Was there a resolution for this? I'm seeing the same problem with v1.4.1 on OSX

**Comment by davibe** [comment] 2016-12-14 17:43
are you sure you re-downloaded packages ? what do you do to make this happen ?

**Comment by solocommand** [comment] 2016-12-14 20:33
@davibe This is with the OSX binary from the 1.4.1 release. Setting up new computer, haven't had a chance to get a working build environment yet :) I can try and build from source when I get a chance, or I can submit a separate ticket for with the error from the console with the release executable

**Comment by davibe** [comment] 2016-12-15 07:25
1.4.1 is a pre-release and even if the number remains the same we update the binaries every few days until it becomes stable. That's why i was asking.

I can't reproduce the issue at the moment.

**Comment by solocommand** [comment] 2016-12-15 13:59
@davibe I was able to reproduce it. I get the following error when logging in with a Google Apps account: 
```viewstate.coffee:60 Warning: could not retrieve message input to store.
view.js:126 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
version.coffee:29 YakYak local version is 1.4.1, released version is 1.4.0
```

Logging in with my gmail account worked fine.

**Comment by averissimo** [comment] 2016-12-22 15:12
@solocommand can you try my comment https://github.com/yakyak/yakyak/issues/518#issuecomment-268818460

and show the results (either there or here)

**Comment by solocommand** [comment] 2016-12-22 17:04
@averissimo with my google apps account, I encountered the following error after logging in (main window stays stuck in `Loading Contacts`)
<img width="991" alt="screen shot 2016-12-22 at 11 01 24 am" src="https://cloud.githubusercontent.com/assets/1778222/21433677/4d2af1be-c836-11e6-9873-b61bd2f7c1e8.png">

**Comment by averissimo** [comment] 2016-12-22 20:11
@solocommand my code was wrong, replace the `:` by `,` commas as it is now.

Anyway, I think I narrowed down the problem with @remizyaka feedback, see the thread #518, despite being more recent it has more information

I'm closing this issue, le'ts continue in #518

**Closed by averissimo** 2016-12-22 20:11 UTC
