### ISSUE TITLE
Enable spell check in Mac OSX?

### ISSUE THREAD

**Issue by uratrtl** [yakyak/yakyak#149] opened 2016-03-09 20:43 UTC
Is there a way to enable os x's built in spell check in yakyak?

**Comment by x-tk** [comment] 2016-03-10 15:29
I'd like to know, also.

**Comment by rjcrouch** [comment] 2016-03-10 22:03
I commented on a java based plugin on an old thread:
https://github.com/yakyak/yakyak/issues/61

I'm more of a designer than a developer but I figured a java based plugin could cross with a coffee based application?

For reference here's the plugin.
http://www.javascriptspellcheck.com/

**Comment by ariu** [comment] 2016-03-21 01:44
https://github.com/atom/electron/issues/3189

**Comment by algesten** [comment] 2016-04-08 20:41
duplicate of #61

**Closed by algesten** 2016-04-08 20:41 UTC
