### ISSUE TITLE
Archived conversations visibility

### ISSUE THREAD

**Issue by aditya-pai** [yakyak/yakyak#351] opened 2016-08-26 02:40 UTC
The conversations that have been archived on google hangouts still appear listed on yakyak.

Also, resizing fonts is slightly counter-intuitive, in the sense that, when you reduce the font size you expect to see a larger number of messages, but in fact, the number of messages that are visible to you without scrolling decreases with decreasing font size.

**Comment by randymorris** [comment] 2016-08-26 14:42
For the hiding of archived chats #252 is already open.

I can't reproduce your second issue.  Decreasing the font size shows more messages for me.

**Comment by davibe** [comment] 2016-09-19 12:21
closing as duplicate

**Closed by davibe** 2016-09-19 12:21 UTC
