### ISSUE TITLE
Code sign Mac binaries.

### ISSUE THREAD

**Issue by williamsjj** [yakyak/yakyak#375] opened 2016-09-14 16:25 UTC
It would be really awesome if the Mac binaries could be code signed. Its pretty painful on El Capitan forward to do the initial launch.

**Comment by jacquescrocker** [comment] 2016-10-02 02:17
whats the workaround to actually opening this?

I had to enable apps for all unknown sources. Clicking "Open Anyways" just errored out.

**Comment by averissimo** [comment] 2016-11-29 20:04
duplicate of #245

**Comment by averissimo** [comment] 2016-11-29 20:05
@jacquescrocker not a osx user, sorry

**Closed by averissimo** 2016-11-29 20:04 UTC
Labels: duplicate

**Comment by williamsjj** [comment] 2016-11-29 20:29
@jacquescrocker Right-click on the YakYak binary, then hold down the Option key while you click "Open". 

That will tell OS X to prompt you to accept the reduced to security rather than refusing to run YakYak. Afterward you can launch normally.
