### ISSUE TITLE
Pasting multi-line text dumps messes up text input

### ISSUE THREAD

**Issue by PSiAU** [yakyak/yakyak#469] opened 2016-12-02 03:38 UTC
When pasting in multi-line text dumps (like log output), the text input area gets messed up.
I'm running v1.4 on a Mac.
To recreate it, paste 28 or more lines worth of text into the text input area. It can even be lines with a single character on it. The more lines past 28 you paste, the messier it gets.
Screenshot attached
![capto_capture 2016-12-02_02-32-35_pm](https://cloud.githubusercontent.com/assets/2519639/20822223/fe0febe6-b89c-11e6-82d8-6f486c890e55.png)

**Comment by averissimo** [comment] 2016-12-02 16:38
known bug :(

duplicate of #242

I'm copying your comment there if you don't mind

**Closed by averissimo** 2016-12-02 16:38 UTC
