### ISSUE TITLE
Double clipboard content on paste

### ISSUE THREAD

**Issue by steven-voorn** [yakyak/yakyak#27] opened 2015-07-02 09:27 UTC
When i paste my clipboard text into the message textfield the text gets pasted twice.

**Comment by maxkueng** [comment] 2015-07-02 13:14
This must be a bug in Electron.

I tried running Yakyak with the "electron-prebuilt" package, which uses Version 0.27.1, by running `./node_modules/electron-prebuilt/cli.js app` and it didn't have the double-paste problem.

Then I created a build with `deploy.sh`, which uses version 0.28.1, and started it and the double-paste problem was there again.

So I changed the Electron version in `deploy.sh` to 0.27.3 and created a build. The double-pasting problem was gone.

My conclusion is that there's a bug in Electron >=v0.28.0 . So I created a small Electron v0.28.1 project with a page that has a textarea with the same attributes as the message field in Yakyak and pasted something. But I couldn't reproduce the issue. I assume it only happens under certain circumstances.

We can file an issue for Electron once we find out how to create an isolated case that reproduces the problem.

My recommendation for a short-term fix would be to downgrade Electron.

**Comment by davibe** [comment] 2015-07-02 19:28
i cannot reproduce please explain how i can reproduce it

**Comment by lw4z** [comment] 2015-07-02 20:03
I don't have electron installed in my system, and the problem too happens.

**Comment by maxkueng** [comment] 2015-07-02 21:01
@davibe: Just copy some text with Ctrl+C and paste it in to the message field with Ctrl+V. I'm on Linux. Maybe it doesn't happen on your OS. What are you running?

@lw4z: You don't have to explicitly install Electron. It comes bundled with Yakyak.

**Comment by lw4z** [comment] 2015-07-02 21:09
I use manjaro linux, and i commented because in my package list do not show electron installed.

**Comment by maxkueng** [comment] 2015-07-02 22:25
@lw4z: Did you install [yakyak](https://aur.archlinux.org/packages/yakyak/) from AUR? If you look at the [PKGBUILD](https://aur.archlinux.org/packages/ya/yakyak/PKGBUILD) you'll see that it doesn't use the "electron" package as a dependency but rather downloads its own copy. This is because Yakyak may not always work with the latest version of Electron but rather with a specific version. The Yakyak PKGBUILD uses the same version as used in [deploy.sh](https://github.com/yakyak/yakyak/blob/fdfd4df17817be9d09b94f9c6b79caec8468ac09/deploy.sh#L8).

**Comment by lw4z** [comment] 2015-07-02 22:32
Ok, I installed from AUR. but my ask is: I need install the package electron from AUR to resolve this problem?

**Comment by maxkueng** [comment] 2015-07-03 00:39
@lw4z: No, installing from AUR will not resolve the problem. The AUR package has the same bug. The problem will be resolved once this issue gets closed. But if you install yakyak from AUR you will automatically get the new releases with your system updates. It will also create a nice shortcut in your menu.

**Comment by lw4z** [comment] 2015-07-03 00:41
@maxkueng: Ok, thanks for helping.

**Comment by davibe** [comment] 2015-07-03 08:28
i use OS X and sometimes i try also on Windows 7 (if i really have to). I could not reproduce this. On Linux I understand things could be more complicated. In general when reporting a bug we need more info on the environment. Unfortunately i don't use Linux but I would love a solution that does not require rolling back electron version as we are already waiting for never releases in order to support more features of the app. If this is an electron bug it needs to be reported there and referenced here.

**Comment by snowiow** [comment] 2015-08-05 13:35
I've got the same problem. Also running Manjaro as os.

**Comment by dare023** [comment] 2015-08-08 13:17
Just to confirm problem on Arch Linux.
Hope will be solved soon

**Comment by Gibbz** [comment] 2015-08-09 11:26
same for me on windows and ubuntu

**Comment by ivantcholakov** [comment] 2015-08-14 08:49
I also have doubled text pasting, Ubuntu 15.04, 64-bit.

**Comment by sbjustin** [comment] 2015-08-14 14:09
I also put an issue when copying from word.  Possibly related https://github.com/yakyak/yakyak/issues/46

**Comment by davibe** [comment] 2015-08-25 09:54
@ivancholakov @gibbz can you please check if one of the two copies of the same content is actually an image instead of pure text ? (you should be able to understand that by selecting and/or dragging it)

**Comment by dare023** [comment] 2015-08-25 09:59
I can normally edit  pasted text, if helps.

**Comment by davibe** [comment] 2015-08-25 10:01
so it may not be related to #46 
thank you @dare023

**Comment by ivantcholakov** [comment] 2015-08-25 10:02
An image is copied twice as far I can see.

**Comment by maxkueng** [comment] 2015-10-25 03:53
This is fixed in #60.

**Closed by maxkueng** 2015-10-25 03:53 UTC
