### ISSUE TITLE
Failed to execute 'appendChild' on 'Node' -- Problem starting 1.4.1 on Win8.1

### ISSUE THREAD

**Issue by remizyaka** [yakyak/yakyak#518] opened 2016-12-20 11:35 UTC
When trying to start app see such error in command line on Windows 8.1.
```
Error on YakYak window:   
 { columnNo: 5,
  error: { code: 'MODULE_NOT_FOUND' },
  lineNo: 457,
  msg: 'Uncaught Error: Cannot find module \'autosize\'',
  url: 'module.js' }
--- End of error message in YakYak window.
```
Program window won't appear but I see yakyak.exe process running

**Comment by davibe** [comment] 2016-12-20 13:29
did you download binaries or have you built it yourself

**Comment by remizyaka** [comment] 2016-12-20 14:07
downloaded binaries, tried both x64 and ia32

**Comment by WiXZlo** [comment] 2016-12-20 19:55
I have some error on my Fedora 25. I download pre-built binary.

**Comment by averissimo** [comment] 2016-12-20 23:53
Confirmed this in Win32 and all the binaries seem to have this problem

Don't know why but there's a folder missing in the `autosize` module

`resources/app/node_modules/autosize/dist`

The win32 binaries have been re-uploaded and are working correctly in my Windows 7 VM (32bits)

@remizyaka can you confirm if the win32 binary are working correctly? _(other binaries are being uploaded)_

**Comment by davibe** [comment] 2016-12-21 07:05
@averissimo This comes from the folter of the machine i used to buid packages
```
ubuntu@Ubuntu-1404-trusty-64-minimal:~/yakyak/dist$ find . -name autosize
./yakyak-linux-x64/resources/app/node_modules/autosize
./YakYak-darwin-x64/YakYak.app/Contents/Resources/app/node_modules/autosize
./YakYak-win32-ia32/resources/app/node_modules/autosize
./YakYak-win32-x64/resources/app/node_modules/autosize
./yakyak-linux-ia32/resources/app/node_modules/autosize
```

this is the zipfile that I uploaded after being unzipped 
```
ubuntu@Ubuntu-1404-trusty-64-minimal:~$ find YakYak-win32-x64/ -name autosize
YakYak-win32-x64/resources/app/node_modules/autosize
ubuntu@Ubuntu-1404-trusty-64-minimal:~$ ls `find YakYak-win32-x64/ -name autosize`
LICENSE.md  changelog.md  package.json  readme.md  src
ubuntu@Ubuntu-1404-trusty-64-minimal:~$
```

**Comment by davibe** [comment] 2016-12-21 07:08
@averissimo on the machine i used to build `yakyak/dist/YakYak-win32-x64` is missing the folder you mention indeed

**Comment by remizyaka** [comment] 2016-12-22 08:13
now it starts, but can't login 
```
2016-12-22 11:11:29 WARN no SAPISID cookie
2016-12-22 11:11:29 WARN no SAPISID cookie
connected 0
Error on YakYak window:
 { columnNo: 18,
  error: {},
  lineNo: 126,
  msg: 'Uncaught TypeError: Failed to execute \'appendChild\' on \'Node\': parameter 1 is not of type \'Node\'.',
  url: 'C:\\Program Files (x86)\\yakyak\\resources\\app\\node_modules\\trifl\\lib\\view.js' }
--- End of error message in YakYak window.
```

**Comment by averissimo** [comment] 2016-12-22 15:08
@remizyaka can you try to debug this?

Open the file `C:\Program Files (x86)\yakyak\resources\app\node_modules\trifl\lib\view.js`

And replace line 126 from

`node.appendChild(vw.el);`

to 

```
try {
node.appendChild(vw.el);
console.log('good': vw.el);
} catch (error) {
console.log('error': vw);
console.log('error': vw.el);
}
```

Then save and start yakyak with `yakyak --debug` (which will show the inspector automatically, if not open the inspector with ctrl+alt+i )

Please create a screenshot of the console tab in the inspector that includes `error:`, such as the image below (please include also the `good`s

![image](https://cloud.githubusercontent.com/assets/211358/21429731/05b6e5a0-c858-11e6-896d-c2860a950d51.png)

**Comment by remizyaka** [comment] 2016-12-22 16:51
changed your code little bit
![scr1](https://cloud.githubusercontent.com/assets/4035725/21433221/0dc74b7c-c880-11e6-80cb-7abc70fbf2fb.png)

**Comment by remizyaka** [comment] 2016-12-22 16:58
![scr2](https://cloud.githubusercontent.com/assets/4035725/21433476/fa19d68e-c880-11e6-870f-768837b1df56.png)

**Comment by averissimo** [comment] 2016-12-22 20:07
@remizyaka do you have a development copy of yakyak that you can change and compile? 

For what I can see the conversation header is producing a bad internal DOM that cannot be rendered

I'd suggest first seeing if this is the problem by replacing `applayout.convhead convhead` by `applayout.convhead null` in the file `src/ui/views/controller.coffee`

__If you don't have a development copy__ then find `resources/app/ui/views/controller.js` in your binary folder and replace `applayout.convhead(convhead);` by `applayout.convhead(null);`

Run it and see if there is still a problem, if there is you might need to use some debugging skills ;)

**Comment by averissimo** [comment] 2016-12-22 20:12
ps. @remizyaka sorry about the typo in my code... it was soooooo wrong! :)

**Comment by solocommand** [comment] 2016-12-23 06:13
@averissimo No luck with the latest binary, I still see the same error with my google apps account on OSX. I'll try and dig into it next week but I won't have time until after the holidays.

**Comment by remizyaka** [comment] 2016-12-23 07:10
still same error, let me know if you need my debugging skills ;)
![scr3](https://cloud.githubusercontent.com/assets/4035725/21448838/03239eaa-c8f8-11e6-8461-27c2c91a0755.png)

**Comment by averissimo** [comment] 2016-12-23 12:14
my bad.. forgot something, uploading new binaries...

you can test the solution by replacing `resources/app/ui/views/controller.js` by [dropbox link](https://dl.dropboxusercontent.com/u/9592943/delete/controller.js)

**Comment by averissimo** [comment] 2016-12-23 12:17
my bad.. forgot something, uploading new binaries...

you can test the solution by replacing `resources/app/ui/views/convhead.js` by [dropbox link](https://dl.dropboxusercontent.com/u/9592943/delete/convhead.js)

**Comment by averissimo** [comment] 2016-12-23 16:04
I forgot something and corrected it earlier today.

Try the binary as it should correct your problem

_ps. I went back and forth with this last comment, but the problem should have been solved since I announced the binaries earlier today after the @remizyaka last  comment (saying "still the same error"_

**Comment by remizyaka** [comment] 2016-12-24 11:56
nope, still same error. Tried to download new binaries and tried to replace resources/app/ui/views/convhead.js with the one you gave.

**Comment by sebasped** [comment] 2016-12-27 12:45
Very same problem here, with de Linux 64 version.

**Comment by sebasped** [comment] 2016-12-27 12:59
I start with --debug, then let me log out, and problem desappear. No idea why or how.

**Comment by davibe** [comment] 2017-01-01 13:37
should be fixed now. Try using latest code from `master` or re-download 1.4.1 binaries

**Closed by davibe** 2017-01-01 13:37 UTC
Labels: bug
