### ISSUE TITLE
User icons broken

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#74] opened 2015-10-26 17:33 UTC
I _think_ this happens when the user doesn't have an icon selected and I manually set them. But google hangouts syncs just fine.

Here's yakyak:
<img width="110" alt="screen shot 2015-10-26 at 10 30 38 am" src="https://cloud.githubusercontent.com/assets/1900880/10736965/e59a18ba-7bcc-11e5-9724-460a31df8038.png">

and here's the same people in hangouts:
<img width="69" alt="screen shot 2015-10-26 at 10 31 55 am" src="https://cloud.githubusercontent.com/assets/1900880/10736968/eda1e736-7bcc-11e5-8d63-f67228f9bf78.png">

the top icon in yakyak should be a penguin...

**Comment by msphair** [comment] 2015-10-26 17:38
Deleting the contents of the application support folder `/Users/Library/Application Support/yakyak` and rebooting solved the issue.

**Comment by kethinov** [comment] 2015-10-26 17:41
I've seen this issue as well.

Thanks for posting the workaround!

**Comment by aaronbieber** [comment] 2016-01-16 13:43
+1, I had this happen with just one particular contact and deleting the application support files fixed it.

**Comment by davibe** [comment] 2016-01-16 22:12
uh. Is there a clear way to reproduce this ?

**Comment by msphair** [comment] 2016-04-22 17:10
I just looked into the inspector when it was broken and then again after I did the work around. Both times, the URL used to grab the image is the same.

However, the broken images have different URL formats than the unaffected ones.

The unstable images pull their images from `https://plus.google.com/_/focus/photos/private/...` and the unaffected images pull from `https://lh3.googleusercontent.com/...`

**Comment by msphair** [comment] 2016-04-22 17:14
maybe a lead?

https://stackoverflow.com/questions/25467326/retrieving-google-user-photo

**Comment by jessejoe** [comment] 2016-08-30 17:44
Workaround for Linux users: `rm -rf ~/.config/yakyak/Cache/`, restart app.

**Comment by averissimo** [comment] 2016-11-29 20:37
@msphair is this still a problem with yakyak?

**Comment by msphair** [comment] 2016-11-29 20:41
I had stopped using yakyak because messages would be delayed sometimes over a minute. I'll give it a try and see if the problem is resolved.

**Comment by jessejoe** [comment] 2016-11-29 20:42
@averissimo speaking for myself, i no longer see broken user icons on `v.1.4.0-beta`, those users seem to have just reverted to initials. User icons seem to be hit or miss with yakyak. Some of them match the ones in pure hangouts, some are just initials, or the incorrect initials.

Example Hangouts:
![image](https://cloud.githubusercontent.com/assets/1694586/20728132/5a921e3e-b64a-11e6-90c5-d03c56d731d4.png)

Example yakyak (note the second AJ should either be an image like in hangouts, or different initials):
![image](https://cloud.githubusercontent.com/assets/1694586/20728150/70320b6e-b64a-11e6-9a59-b862dc5d6c91.png)

**Comment by averissimo** [comment] 2016-11-29 20:46
Does the missing initials also appear missing in the chat window?

I was going through my contact list to see if I could replicate this, and found a contact like that

![image](https://cloud.githubusercontent.com/assets/211358/20728294/e5a1e93a-b674-11e6-86d0-8af19621c1c2.png)

**Comment by msphair** [comment] 2016-11-29 20:47
still happening. I loaded up the v1.3.3 pre-release and cleared the cache using https://github.com/yakyak/yakyak/issues/74#issuecomment-243520822

the contact list is mostly better with the occasional:
<img width="68" alt="screen shot 2016-11-29 at 12 45 57 pm" src="https://cloud.githubusercontent.com/assets/1900880/20728287/d3f78174-b631-11e6-8597-59de9069eebd.png">

the the same problematic contacts are still broken in the actual chat:

contact list:
<img width="62" alt="screen shot 2016-11-29 at 12 46 56 pm" src="https://cloud.githubusercontent.com/assets/1900880/20728309/ef22ff78-b631-11e6-8f0b-2da0b9c27dfe.png">

chat:
<img width="70" alt="screen shot 2016-11-29 at 12 47 19 pm" src="https://cloud.githubusercontent.com/assets/1900880/20728317/fa8ba46e-b631-11e6-8368-4ae70043ef54.png">

**Comment by jessejoe** [comment] 2016-11-29 20:49
@averissimo actually, no the image is correct in the chat window. Just the userlist is wrong.

**Comment by averissimo** [comment] 2016-11-29 20:51
@msphair wow thanks for being so fast :)

we're testing a beta version in #451 that partially corrects that problem, but as jessejoe showed (and I just confirmed) there are still incorrect initials

@jessejoe thanks!! I was not happy with the solution but until now I thought it was working.. this is the opportunity to do it right!! :)

**Comment by averissimo** [comment] 2016-11-30 01:57
@jessejoe can you try beta4?

available here: https://github.com/averissimo/yakyak/releases/tag/v1.4.0-beta4

**Comment by jessejoe** [comment] 2016-11-30 13:36
@averissimo I think that build is bad, tried downloading/extracting multiple times:

![image](https://cloud.githubusercontent.com/assets/1694586/20754257/180bb136-b6d8-11e6-88ad-f7b38445f758.png)

**Comment by jessejoe** [comment] 2016-11-30 13:42
@averissimo also I just noticed after reinstalling/reopening beta 3, my contact that was wrong is now correct. I also noticed this on another machine I had yakyak installed. I wonder if it was just a cached issue?

**Comment by averissimo** [comment] 2016-11-30 21:58
I experienced the same thing with my broken contact, have no idea why, maybe cached

anyway, this new implementation is much better

can you try again to use beta4 ? it was made using a new packaging method.. more robust and flexible yay 

(it will allow for signed binaries in osx... not this one though as I generated it myself in Linux)

https://github.com/averissimo/yakyak/releases/tag/v1.4.0-beta4

(this will probably be the last beta hosted in my fork and I'll do it in yakyak from now on)

**Comment by averissimo** [comment] 2016-11-30 22:00
@msphair can you try beta4 link below.. there should no be any more weird avatars :)

https://github.com/averissimo/yakyak/releases/tag/v1.4.0-beta4

**Comment by jessejoe** [comment] 2016-11-30 22:04
@averissimo this build doesn't work either:

![image](https://cloud.githubusercontent.com/assets/1694586/20773286/1005310a-b71f-11e6-9707-aee4605336bd.png)

**Comment by averissimo** [comment] 2016-12-01 21:53
@jessejoe can you try beta4 please? I promise you this is working

ps. in fact due to this problems we moved to a more robust and predictable method of generating binaries.

**Comment by jessejoe** [comment] 2016-12-01 21:56
@averissimo actually I noticed the release this morning and have been using it all day. No problems so far!

**Comment by averissimo** [comment] 2016-12-01 22:04
@msphair **if you can give feedback on how it looks in your system** we can close this issue and merge this to master?

**Comment by averissimo** [comment] 2016-12-01 22:04
@jessejoe \o/ great!!

**Comment by msphair** [comment] 2016-12-05 16:20
Looks good overall. There's an initial flicker when I switch to a conversation that was broken where it shows the broken image very quickly then overrides with just the initials in the circle.

**Comment by averissimo** [comment] 2016-12-05 17:38
Good!! 

Still can't figure out why the flikr, but this way it works really well

**Comment by averissimo** [comment] 2016-12-23 00:59
available in 1.4.0

please open a new issue if there is any problem

**Closed by averissimo** 2016-12-23 00:59 UTC
Labels: bug
