### ISSUE TITLE
YakYak Breaking when pasting "C# Code"

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [yakyak/yakyak#595] opened 2017-02-15 11:43 UTC
Hello there,

I tried to send a snippet to my coworker and YakYak "didn't like it"

Here's the text I tried to send : 
```
// COUNTERS
                try
                {
                    _cpuCounter = new PerformanceCounter
                    {
                        CategoryName = "Processor",
                        CounterName = "% Processor Time",
                        InstanceName = "_Total"
                    };
                    _ramCounter = new PerformanceCounter("Memory", "Available Bytes");
                }
                catch (Exception ex2)
                {
                    // If counter fails, rebuilding
                    MessageBoxShow("Performance counter probably corrupted, rebuilding..." + ex2,false);
                    var process = new Process();
                    var startInfo = new ProcessStartInfo
                    {
                        WindowStyle = ProcessWindowStyle.Hidden,
                        FileName = "cmd.exe",
                        Arguments = "/C lodctr /r",
                        Verb = "runas"
                    };
                    process.StartInfo = startInfo;
                    process.Start();
                    process.WaitForExit(); // Waiting for lodctr to rebuild counters
                    // We try again...
                    try
                    {
                        _cpuCounter = new PerformanceCounter
                        {
                            CategoryName = "Processor",
                            CounterName = "% Processor Time",
                            InstanceName = "_Total"
                        };
                        _ramCounter = new PerformanceCounter("Memory", "Available Bytes");
                    }
                    catch (Exception exception)
                    {
                        MessageBoxShow(exception.ToString(),true);
                    }
                    
                }
```
![error1](https://cloud.githubusercontent.com/assets/4887819/22972955/43d75c3a-f37c-11e6-8a60-baa8254713e4.PNG)
![error2](https://cloud.githubusercontent.com/assets/4887819/22972954/43d20e42-f37c-11e6-9ab8-59f6c1c12a53.PNG)

**Comment by averissimo** [comment] 2017-02-16 17:55
it's not the code part, it's the number of lines in a single message.

it messes the ui :\

duplicate of #242 (i'm closing this issue in favor of 242)

**Closed by averissimo** 2017-02-16 17:55 UTC
