### ISSUE TITLE
Blank screen, Js errors

### ISSUE THREAD

**Issue by digiwizkid** [yakyak/yakyak#136] opened 2016-02-12 12:34 UTC
![yakyak blank screen](https://cloud.githubusercontent.com/assets/16302424/13007011/052526a2-d1b3-11e5-82b6-d86d52dacd5b.png)

**Comment by Georgeto** [comment] 2016-02-12 12:35
duplicate of #130

**Comment by digiwizkid** [comment] 2016-02-12 12:44
Using ubuntu 14.04,
worked fine on the first run able to login & check messages, next run onwards facing this issue.

**Comment by davibe** [comment] 2016-02-13 11:05
than you @Georgeto for keeping track of things. Next release should fix this

**Comment by mk30** [comment] 2016-02-17 08:02
![2016-02-16-234944_1366x768_scrot](https://cloud.githubusercontent.com/assets/4651439/13103127/810cd780-d508-11e5-8b00-4ca3027d0756.png)

app stays in the bottom of the screen, and slowly slides down there if i try to move it. is this behavior part of this issue?

i'm on lubuntu 14.04.3

**Comment by yermulnik** [comment] 2016-02-24 21:07
Same here (Linux Mint 17.1 Rebecca)

**Comment by nhodges** [comment] 2016-03-25 22:17
I'm getting blank screen, no js errors to speak of in inspector.

**Comment by nhodges** [comment] 2016-03-25 22:18
Also, now that its in this state, I get notifications from myself (when I'm talking to others in the web version of Hangouts)

**Comment by digiwizkid** [comment] 2016-03-26 08:04
Currently using fork by @ariu [yakyak](https://github.com/ariu/yakyak). Works perfectly fine.

**Comment by yermulnik** [comment] 2016-03-26 12:21
@digiwizkid thanx for the hint - I'll try that fork (looks a little bit attractively) =)

**Comment by algesten** [comment] 2016-04-08 20:34
#160 fixes this then?

**Closed** 2016-06-08 08:41 UTC
Labels: bug
