### ISSUE TITLE
yak yak wont start

### ISSUE THREAD

**Issue by epizarro2** [yakyak/yakyak#1178] opened 2020-06-16 14:16 UTC
![image](https://user-images.githubusercontent.com/49302511/84786149-5b5fbc00-afba-11ea-9aac-8558353bd2fc.png)

After reboot yak yak doesn't start, what can i do, just appears in task manager but not in tray

**Comment by epizarro2** [comment] 2020-06-16 14:19
also, there isn't a log path to see whats its doing

**Comment by epizarro2** [comment] 2020-06-16 14:20
after removing %appdata% folder, yask yak stuck at login

![image](https://user-images.githubusercontent.com/49302511/84786644-053f4880-afbb-11ea-8991-4d5014924a25.png)

**Comment by fgladu** [comment] 2020-06-16 14:21
I think it's Google...

**Comment by epizarro2** [comment] 2020-06-16 14:32
np, going back to chrome plugin

**Comment by xtrimsky** [comment] 2020-06-16 14:39
same issue on Mac OS X build. Probably a change on the Google side. Don't forget Google is planning to drop support for Google Hangouts.

**Comment by adampatterson** [comment] 2020-06-16 16:17
I have the same problem. Last time I think there was an issue with Google.

**Comment by HomerSp** [comment] 2020-06-16 16:55
See #1177 for the cause and a solution to it not connecting.

**Comment by WinterWerewolf** [comment] 2020-06-16 17:03
Same here. Stuck at Connecting screen.

**Comment by averissimo** [comment] 2020-06-16 17:47
Should be fixed in v1.5.7 thanks to @HomerSp

**Closed by averissimo** 2020-06-16 17:47 UTC
