### ISSUE TITLE
When pinned to taskbar, shift click on icon

### ISSUE THREAD

**Issue by nathanharperdev** [yakyak/yakyak#298] opened 2016-06-30 13:48 UTC
Resulting Error:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EBUSY: resource busy or locked, unlink 'C:\Users\user\AppData\Roaming\yakyak\Cookies'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1093:18)
    at Object.<anonymous> (C:\Users\user\Downloads\yakyak-win32-x64\win32-x64\resources\app\main.js:50:8)
    at Object.<anonymous> (C:\Users\user\Downloads\yakyak-win32-x64\win32-x64\resources\app\main.js:450:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Object.<anonymous> (C:\Users\user\Downloads\yakyak-win32-x64\win32-x64\resources\electron.asar\browser\init.js:180:8)

[OK]
```

Does not occur if icon is not pinned.

**Comment by averissimo** [comment] 2016-12-23 00:14
is this still an issue?

I guess by shift+click you are trying to start a new instance of yakyak, and it gives out that errer

**Comment by averissimo** [comment] 2016-12-23 00:20
@nathanharperdev duplicate of #258 -- let's continue there

**Closed by averissimo** 2016-12-23 00:20 UTC
Labels: bug, help wanted
